import { NextResponse } from "next/server";
import { getAIRecommendations } from "@/lib/sensor-integration-service";
import { requireApiAccess } from "@/lib/billing/require-access";

/**
 * GET /api/sensors/ai
 * Returns AI recommendations generated by combining sensor data with
 * weather, satellite, crop, and historical field data.
 */
export async function GET() {
  // Protected: requires auth + verified email + active subscription.
  const denied = await requireApiAccess();
  if (denied) return denied;

  try {
    const recommendations = await getAIRecommendations();
    return NextResponse.json({ recommendations });
  } catch (error) {
    console.error("Failed to fetch AI recommendations:", error);
    return NextResponse.json({ error: "Failed to fetch AI recommendations" }, { status: 500 });
  }
}
