"use client";

import { createContext, useContext, useEffect, useState } from "react";
import i18next from "i18next";

export type AppLanguage = "en" | "es" | "fr" | "de" | "it" | "pt" | "nl" | "ar" | "el" | "zh" | "ja";

export interface LanguageOption {
  value: AppLanguage;
  label: string;
  nativeLabel: string;
}

export const languageOptions: LanguageOption[] = [
  { value: "en", label: "English", nativeLabel: "English" },
  { value: "es", label: "Spanish", nativeLabel: "Español" },
  { value: "fr", label: "French", nativeLabel: "Français" },
  { value: "de", label: "German", nativeLabel: "Deutsch" },
  { value: "it", label: "Italian", nativeLabel: "Italiano" },
  { value: "pt", label: "Portuguese", nativeLabel: "Português" },
  { value: "nl", label: "Dutch", nativeLabel: "Nederlands" },
  { value: "ar", label: "Arabic", nativeLabel: "العربية" },
  { value: "el", label: "Greek", nativeLabel: "Ελληνικά" },
  { value: "zh", label: "Chinese", nativeLabel: "中文" },
  { value: "ja", label: "Japanese", nativeLabel: "日本語" },
];

const translations: Record<string, Record<AppLanguage, string>> = {
  "settings.title": {
    en: "Settings",
    es: "Configuración",
    fr: "Paramètres",
    de: "Einstellungen",
    it: "Impostazioni",
    pt: "Configurações",
    nl: "Instellingen",
    ar: "الإعدادات",
    el: "Ρυθμίσεις",
    zh: "设置",
    ja: "設定",
  },
  "settings.description": {
    en: "Manage your account and application preferences",
    es: "Administra tu cuenta y las preferencias de la aplicación",
    fr: "Gérez votre compte et les préférences de l'application",
    de: "Verwalten Sie Ihr Konto und die Anwendungseinstellungen",
    it: "Gestisci il tuo account e le preferenze dell'app",
    pt: "Gerencie sua conta e as preferências do aplicativo",
    nl: "Beheer uw account en app-voorkeuren",
    ar: "إدارة حسابك وتفضيلات التطبيق",
    el: "Διαχειριστείτε τον λογαριασμό σας και τις προτιμήσεις της εφαρμογής",
    zh: "管理您的账户和应用偏好",
    ja: "アカウントとアプリの設定を管理する",
  },
  "tabs.general": {
    en: "General",
    es: "General",
    fr: "Général",
    de: "Allgemein",
    it: "Generale",
    pt: "Geral",
    nl: "Algemeen",
    ar: "عام",
    el: "Γενικά",
    zh: "常规",
    ja: "一般",
  },
  "tabs.profile": {
    en: "Profile",
    es: "Perfil",
    fr: "Profil",
    de: "Profil",
    it: "Profilo",
    pt: "Perfil",
    nl: "Profiel",
    ar: "الملف الشخصي",
    el: "Προφίλ",
    zh: "个人资料",
    ja: "プロフィール",
  },
  "tabs.notifications": {
    en: "Notifications",
    es: "Notificaciones",
    fr: "Notifications",
    de: "Benachrichtigungen",
    it: "Notifiche",
    pt: "Notificações",
    nl: "Meldingen",
    ar: "الإشعارات",
    el: "Ειδοποιήσεις",
    zh: "通知",
    ja: "通知",
  },
  "tabs.security": {
    en: "Security",
    es: "Seguridad",
    fr: "Sécurité",
    de: "Sicherheit",
    it: "Sicurezza",
    pt: "Segurança",
    nl: "Beveiliging",
    ar: "الأمان",
    el: "Ασφάλεια",
    zh: "安全",
    ja: "セキュリティ",
  },
  "tabs.team": {
    en: "Team",
    es: "Equipo",
    fr: "Équipe",
    de: "Team",
    it: "Team",
    pt: "Equipe",
    nl: "Team",
    ar: "الفريق",
    el: "Ομάδα",
    zh: "团队",
    ja: "チーム",
  },
  "appearance.title": {
    en: "Appearance",
    es: "Apariencia",
    fr: "Apparence",
    de: "Erscheinungsbild",
    it: "Aspetto",
    pt: "Aparência",
    nl: "Weergave",
    ar: "المظهر",
    el: "Εμφάνιση",
    zh: "外观",
    ja: "外観",
  },
  "appearance.theme": {
    en: "Theme",
    es: "Tema",
    fr: "Thème",
    de: "Thema",
    it: "Tema",
    pt: "Tema",
    nl: "Thema",
    ar: "السمة",
    el: "Θέμα",
    zh: "主题",
    ja: "テーマ",
  },
  "appearance.currency": {
    en: "Currency",
    es: "Moneda",
    fr: "Devise",
    de: "Währung",
    it: "Valuta",
    pt: "Moeda",
    nl: "Valuta",
    ar: "العملة",
    el: "Νόμισμα",
    zh: "货币",
    ja: "通貨",
  },
  "appearance.language": {
    en: "Language",
    es: "Idioma",
    fr: "Langue",
    de: "Sprache",
    it: "Lingua",
    pt: "Idioma",
    nl: "Taal",
    ar: "اللغة",
    el: "Γλώσσα",
    zh: "语言",
    ja: "言語",
  },
  "appearance.units": {
    en: "Units",
    es: "Unidades",
    fr: "Unités",
    de: "Einheiten",
    it: "Unità",
    pt: "Unidades",
    nl: "Eenheden",
    ar: "الوحدات",
    el: "Μονάδες",
    zh: "单位",
    ja: "単位",
  },
  "appearance.languageHint": {
    en: "Choose the language used across the dashboard.",
    es: "Elige el idioma utilizado en el panel.",
    fr: "Choisissez la langue utilisée dans le tableau de bord.",
    de: "Wählen Sie die Sprache für das Dashboard.",
    it: "Scegli la lingua usata nella dashboard.",
    pt: "Escolha o idioma usado no painel.",
    nl: "Kies de taal die in het dashboard wordt gebruikt.",
    ar: "اختر اللغة المستخدمة في لوحة المعلومات.",
    el: "Επιλέξτε τη γλώσσα που χρησιμοποιείται στο dashboard.",
    zh: "选择仪表板使用的语言。",
    ja: "ダッシュボードで使用する言語を選択します。",
  },
  "nav.dashboard": {
    en: "Dashboard",
    es: "Panel",
    fr: "Tableau de bord",
    de: "Dashboard",
    it: "Dashboard",
    pt: "Painel",
    nl: "Dashboard",
    ar: "لوحة المعلومات",
    el: "Πίνακας Ελέγχου",
    zh: "仪表板",
    ja: "ダッシュボード",
  },
  "nav.farmMap": {
    en: "Farm Map",
    es: "Mapa de la finca",
    fr: "Carte de la ferme",
    de: "Farmkarte",
    it: "Mappa azienda",
    pt: "Mapa da fazenda",
    nl: "Boerderijkaart",
    ar: "خريطة المزرعة",
    el: "Χάρτης Αγροκτήματος",
    zh: "农场地图",
    ja: "農場マップ",
  },
  "nav.weather": {
    en: "Weather",
    es: "Clima",
    fr: "Météo",
    de: "Wetter",
    it: "Meteo",
    pt: "Tempo",
    nl: "Weer",
    ar: "الطقس",
    el: "Καιρός",
    zh: "天气",
    ja: "天気",
  },
  "nav.sensors": {
    en: "Sensors",
    es: "Sensores",
    fr: "Capteurs",
    de: "Sensoren",
    it: "Sensori",
    pt: "Sensores",
    nl: "Sensoren",
    ar: "الأجهزة الاستشعار",
    el: "Αισθητήρες",
    zh: "传感器",
    ja: "センサー",
  },
  "nav.fields": {
    en: "Fields",
    es: "Campos",
    fr: "Champs",
    de: "Felder",
    it: "Campi",
    pt: "Talhões",
    nl: "Percelen",
    ar: "الحقول",
    el: "Αγροτεμάχια",
    zh: "田地",
    ja: "圃場",
  },
  "nav.calendar": {
    en: "Calendar",
    es: "Calendario",
    fr: "Calendrier",
    de: "Kalender",
    it: "Calendario",
    pt: "Calendário",
    nl: "Agenda",
    ar: "التقويم",
    el: "Ημερολόγιο",
    zh: "日历",
    ja: "カレンダー",
  },
  "nav.inventory": {
    en: "Inventory",
    es: "Inventario",
    fr: "Inventaire",
    de: "Inventar",
    it: "Inventario",
    pt: "Estoque",
    nl: "Voorraad",
    ar: "المخزون",
    el: "Απόθεμα",
    zh: "库存",
    ja: "在庫",
  },
  "nav.animals": {
    en: "Animals",
    es: "Animales",
    fr: "Animaux",
    de: "Tiere",
    it: "Animali",
    pt: "Animais",
    nl: "Dieren",
    ar: "الحيوانات",
    el: "Ζώα",
    zh: "动物",
    ja: "動物",
  },
  "nav.machinery": {
    en: "Machinery",
    es: "Maquinaria",
    fr: "Machinisme",
    de: "Maschinen",
    it: "Macchinari",
    pt: "Máquinas",
    nl: "Machines",
    ar: "الآلات",
    el: "Μηχανήματα",
    zh: "机械",
    ja: "機械",
  },
  "nav.workers": {
    en: "Workers",
    es: "Trabajadores",
    fr: "Employés",
    de: "Mitarbeiter",
    it: "Operatori",
    pt: "Trabalhadores",
    nl: "Werknemers",
    ar: "العاملون",
    el: "Εργαζόμενοι",
    zh: "工人",
    ja: "作業員",
  },
  "nav.marketplace": {
    en: "Marketplace",
    es: "Mercado",
    fr: "Marché",
    de: "Marktplatz",
    it: "Marketplace",
    pt: "Mercado",
    nl: "Marktplaats",
    ar: "السوق",
    el: "Αγορά",
    zh: "市场",
    ja: "マーケットプレイス",
  },
  "nav.analytics": {
    en: "Analytics",
    es: "Analítica",
    fr: "Analytique",
    de: "Analytik",
    it: "Analisi",
    pt: "Análises",
    nl: "Analyse",
    ar: "التحليلات",
    el: "Αναλύσεις",
    zh: "分析",
    ja: "分析",
  },
  "nav.finance": {
    en: "Finance",
    es: "Finanzas",
    fr: "Finances",
    de: "Finanzen",
    it: "Finanze",
    pt: "Finanças",
    nl: "Financiën",
    ar: "المالية",
    el: "Οικονομικά",
    zh: "财务",
    ja: "財務",
  },
  "nav.aiAssistant": {
    en: "AI Assistant",
    es: "Asistente de IA",
    fr: "Assistant IA",
    de: "KI-Assistent",
    it: "Assistente IA",
    pt: "Assistente de IA",
    nl: "AI-assistent",
    ar: "مساعد الذكاء الاصطناعي",
    el: "Βοηθός AI",
    zh: "AI 助手",
    ja: "AIアシスタント",
  },
  "nav.notifications": {
    en: "Notifications",
    es: "Notificaciones",
    fr: "Notifications",
    de: "Benachrichtigungen",
    it: "Notifiche",
    pt: "Notificações",
    nl: "Meldingen",
    ar: "الإشعارات",
    el: "Ειδοποιήσεις",
    zh: "通知",
    ja: "通知",
  },
  "nav.settings": {
    en: "Settings",
    es: "Configuración",
    fr: "Paramètres",
    de: "Einstellungen",
    it: "Impostazioni",
    pt: "Configurações",
    nl: "Instellingen",
    ar: "الإعدادات",
    el: "Ρυθμίσεις",
    zh: "设置",
    ja: "設定",
  },
  "nav.logout": {
    en: "Logout",
    es: "Cerrar sesión",
    fr: "Se déconnecter",
    de: "Abmelden",
    it: "Disconnetti",
    pt: "Sair",
    nl: "Uitloggen",
    ar: "تسجيل الخروج",
    el: "Αποσύνδεση",
    zh: "退出登录",
    ja: "ログアウト",
  },
  "nav.searchPlaceholder": {
    en: "Search fields, tasks, machinery...",
    es: "Buscar campos, tareas, maquinaria...",
    fr: "Rechercher des champs, tâches, machines...",
    de: "Suche Felder, Aufgaben, Maschinen...",
    it: "Cerca campi, attività, macchinari...",
    pt: "Pesquisar talhões, tarefas, máquinas...",
    nl: "Zoek percelen, taken, machines...",
    ar: "ابحث عن الحقول والمهام والآلات...",
    el: "Αναζήτηση αγροτεμαχίων, εργασιών, μηχανημάτων...",
    zh: "搜索田地、任务、机械...",
    ja: "圃場、タスク、機械を検索...",
  },
  "nav.online": {
    en: "Online",
    es: "En línea",
    fr: "En ligne",
    de: "Online",
    it: "Online",
    pt: "Online",
    nl: "Online",
    ar: "متصل",
    el: "Συνδεδεμένος",
    zh: "在线",
    ja: "オンライン",
  },
  "nav.offline": {
    en: "Offline",
    es: "Sin conexión",
    fr: "Hors ligne",
    de: "Offline",
    it: "Offline",
    pt: "Offline",
    nl: "Offline",
    ar: "غير متصل",
    el: "Εκτός σύνδεσης",
    zh: "离线",
    ja: "オフライン",
  },
  "nav.install": {
    en: "Install",
    es: "Instalar",
    fr: "Installer",
    de: "Installieren",
    it: "Installa",
    pt: "Instalar",
    nl: "Installeren",
    ar: "تثبيت",
    el: "Εγκατάσταση",
    zh: "安装",
    ja: "インストール",
  },
  "nav.profileTitle": {
    en: "Alex Driver",
    es: "Alex Driver",
    fr: "Alex Driver",
    de: "Alex Driver",
    it: "Alex Driver",
    pt: "Alex Driver",
    nl: "Alex Driver",
    ar: "أليكس دريفر",
    el: "Αλεξ Ντράιβερ",
    zh: "Alex Driver",
    ja: "アレックス・ドライバー",
  },
  "nav.profileSubtitle": {
    en: "Farm Manager",
    es: "Gerente de finca",
    fr: "Gestionnaire de ferme",
    de: "Farmmanager",
    it: "Responsabile azienda",
    pt: "Gerente da fazenda",
    nl: "Boerderijmanager",
    ar: "مدير المزرعة",
    el: "Διαχειριστής Αγροκτήματος",
    zh: "农场经理",
    ja: "ファームマネージャー",
  },
  "landing.signIn": {
    en: "Sign In",
    es: "Iniciar sesión",
    fr: "Se connecter",
    de: "Anmelden",
    it: "Accedi",
    pt: "Entrar",
    nl: "Inloggen",
    ar: "تسجيل الدخول",
    el: "Σύνδεση",
    zh: "登录",
    ja: "サインイン",
  },
  "landing.getStarted": {
    en: "Get Started",
    es: "Comenzar",
    fr: "Commencer",
    de: "Loslegen",
    it: "Inizia",
    pt: "Começar",
    nl: "Aan de slag",
    ar: "ابدأ الآن",
    el: "Έναρξη",
    zh: "开始使用",
    ja: "始める",
  },
  "landing.features": {
    en: "Features",
    es: "Funciones",
    fr: "Fonctionnalités",
    de: "Funktionen",
    it: "Funzionalità",
    pt: "Recursos",
    nl: "Functies",
    ar: "الميزات",
    el: "Χαρακτηριστικά",
    zh: "功能",
    ja: "機能",
  },
  "landing.dashboard": {
    en: "Dashboard",
    es: "Panel",
    fr: "Tableau de bord",
    de: "Dashboard",
    it: "Dashboard",
    pt: "Painel",
    nl: "Dashboard",
    ar: "لوحة المعلومات",
    el: "Πίνακας Ελέγχου",
    zh: "仪表板",
    ja: "ダッシュボード",
  },
  "landing.pricing": {
    en: "Pricing",
    es: "Precios",
    fr: "Tarifs",
    de: "Preise",
    it: "Prezzi",
    pt: "Preços",
    nl: "Prijzen",
    ar: "الأسعار",
    el: "Τιμολόγηση",
    zh: "价格",
    ja: "料金",
  },
  "landing.faq": {
    en: "FAQ",
    es: "Preguntas frecuentes",
    fr: "FAQ",
    de: "FAQ",
    it: "FAQ",
    pt: "Perguntas frequentes",
    nl: "Veelgestelde vragen",
    ar: "الأسئلة الشائعة",
    el: "Συχνές Ερωτήσεις",
    zh: "常见问题",
    ja: "FAQ",
  },
"auth.backHome": {
    en: "Back to home",
    es: "Volver al inicio",
    fr: "Retour à l'accueil",
    de: "Zurück zur Startseite",
    it: "Torna alla home",
    pt: "Voltar para o início",
    nl: "Terug naar home",
    ar: "العودة إلى الصفحة الرئيسية",
    el: "Επιστροφή στην αρχική",
    zh: "返回首页",
    ja: "ホームへ戻る",
  },
  "auth.backLogin": {
    en: "Back to login",
    es: "Volver al inicio de sesión",
    fr: "Retour à la connexion",
    de: "Zurück zum Anmelden",
    it: "Torna al login",
    pt: "Voltar para o login",
    nl: "Terug naar inloggen",
    ar: "العودة إلى تسجيل الدخول",
    el: "Επιστροφή στη σύνδεση",
    zh: "返回登录",
    ja: "ログインに戻る",
  },
  "auth.welcomeBack": {
    en: "Welcome back",
    es: "Bienvenido de nuevo",
    fr: "Bon retour",
    de: "Willkommen zurück",
    it: "Bentornato",
    pt: "Bem-vindo de volta",
    nl: "Welkom terug",
    ar: "مرحبًا بعودتك",
    el: "Καλωσήρθες ξανά",
    zh: "欢迎回来",
    ja: "おかえりなさい",
  },
  "auth.signInToContinue": {
    en: "Sign in to your account to continue",
    es: "Inicia sesión en tu cuenta para continuar",
    fr: "Connectez-vous à votre compte pour continuer",
    de: "Melden Sie sich bei Ihrem Konto an, um fortzufahren",
    it: "Accedi al tuo account per continuare",
    pt: "Faça login na sua conta para continuar",
    nl: "Log in op uw account om door te gaan",
    ar: "سجّل الدخول إلى حسابك للمتابعة",
    el: "Συνδεθείτε στο λογαριασμό σας για να συνεχίσετε",
    zh: "登录您的账户以继续",
    ja: "アカウントにサインインして続行",
  },
  "auth.email": {
    en: "Email",
    es: "Correo electrónico",
    fr: "E-mail",
    de: "E-Mail",
    it: "Email",
    pt: "E-mail",
    nl: "E-mail",
    ar: "البريد الإلكتروني",
    el: "Email",
    zh: "电子邮件",
    ja: "メール",
  },
  "auth.password": {
    en: "Password",
    es: "Contraseña",
    fr: "Mot de passe",
    de: "Passwort",
    it: "Password",
    pt: "Senha",
    nl: "Wachtwoord",
    ar: "كلمة المرور",
    el: "Κωδικός πρόσβασης",
    zh: "密码",
    ja: "パスワード",
  },
  "auth.rememberMe": {
    en: "Remember me",
    es: "Recuérdame",
    fr: "Se souvenir de moi",
    de: "Angemeldet bleiben",
    it: "Ricordami",
    pt: "Lembrar de mim",
    nl: "Onthoud mij",
    ar: "تذكرني",
    el: "Θυμήσου με",
    zh: "记住我",
    ja: "ログイン情報を保存",
  },
  "auth.forgotPassword": {
    en: "Forgot password?",
    es: "¿Olvidaste tu contraseña?",
    fr: "Mot de passe oublié ?",
    de: "Passwort vergessen?",
    it: "Password dimenticata?",
    pt: "Esqueceu a senha?",
    nl: "Wachtwoord vergeten?",
    ar: "هل نسيت كلمة المرور؟",
    el: "Ξεχάσατε τον κωδικό σας;",
    zh: "忘记密码？",
    ja: "パスワードをお忘れですか？",
  },
  "auth.signIn": {
    en: "Sign In",
    es: "Iniciar sesión",
    fr: "Se connecter",
    de: "Anmelden",
    it: "Accedi",
    pt: "Entrar",
    nl: "Inloggen",
    ar: "تسجيل الدخول",
    el: "Σύνδεση",
    zh: "登录",
    ja: "サインイン",
  },
  "auth.noAccount": {
    en: "Don't have an account?",
    es: "¿No tienes una cuenta?",
    fr: "Vous n'avez pas de compte ?",
    de: "Sie haben noch kein Konto?",
    it: "Non hai un account?",
    pt: "Não tem uma conta?",
    nl: "Heeft u geen account?",
    ar: "لا تملك حسابًا؟",
    el: "Δεν έχετε λογαριασμό;",
    zh: "没有账户？",
    ja: "アカウントをお持ちではありませんか？",
  },
  "auth.signUp": {
    en: "Sign up",
    es: "Registrarse",
    fr: "S'inscrire",
    de: "Registrieren",
    it: "Registrati",
    pt: "Cadastre-se",
    nl: "Aanmelden",
    ar: "إنشاء حساب",
    el: "Εγγραφή",
    zh: "注册",
    ja: "サインアップ",
  },
  "auth.createAccount": {
    en: "Create your account",
    es: "Crea tu cuenta",
    fr: "Créer votre compte",
    de: "Erstellen Sie Ihr Konto",
    it: "Crea il tuo account",
    pt: "Crie sua conta",
    nl: "Maak uw account aan",
    ar: "أنشئ حسابك",
    el: "Δημιουργήστε τον λογαριασμό σας",
    zh: "创建您的账户",
    ja: "アカウントを作成",
  },
  "auth.createAccountSubtitle": {
    en: "Start your 14-day free trial. No credit card required.",
    es: "Comienza tu prueba gratuita de 14 días. No se requiere tarjeta de crédito.",
    fr: "Commencez votre essai gratuit de 14 jours. Aucune carte de crédit requise.",
    de: "Starten Sie Ihre 14-tägige kostenlose Testversion. Keine Kreditkarte erforderlich.",
    it: "Inizia la tua prova gratuita di 14 giorni. Nessuna carta di credito richiesta.",
    pt: "Comece seu teste gratuito de 14 dias. Nenhum cartão de crédito é necessário.",
    nl: "Start uw 14-daagse gratis proefperiode. Geen creditcard vereist.",
    ar: "ابدأ تجربتك المجانية لمدة 14 يومًا. لا حاجة إلى بطاقة ائتمان.",
    el: "Ξεκινήστε τη δωρεάν δοκιμή 14 ημερών. Δεν απαιτείται πιστωτική κάρτα.",
    zh: "开始14天免费试用。无需信用卡。",
    ja: "14日間の無料トライアルを始めましょう。クレジットカード不要。",
  },
  "auth.fullName": {
    en: "Full Name",
    es: "Nombre completo",
    fr: "Nom complet",
    de: "Vollständiger Name",
    it: "Nome completo",
    pt: "Nome completo",
    nl: "Volledige naam",
    ar: "الاسم الكامل",
    el: "Πλήρες όνομα",
    zh: "全名",
    ja: "フルネーム",
  },
  "auth.createAccountButton": {
    en: "Create Account",
    es: "Crear cuenta",
    fr: "Créer un compte",
    de: "Konto erstellen",
    it: "Crea account",
    pt: "Criar conta",
    nl: "Account aanmaken",
    ar: "إنشاء حساب",
    el: "Δημιουργία λογαριασμού",
    zh: "创建账户",
    ja: "アカウントを作成",
  },
  "auth.alreadyHaveAccount": {
    en: "Already have an account?",
    es: "¿Ya tienes una cuenta?",
    fr: "Vous avez déjà un compte ?",
    de: "Sie haben bereits ein Konto?",
    it: "Hai già un account?",
    pt: "Já tem uma conta?",
    nl: "Heeft u al een account?",
    ar: "هل لديك حساب بالفعل؟",
    el: "Έχετε ήδη λογαριασμό;",
    zh: "已有账户？",
    ja: "すでにアカウントをお持ちですか？",
  },
  "auth.forgotPasswordTitle": {
    en: "Forgot password?",
    es: "¿Olvidaste tu contraseña?",
    fr: "Mot de passe oublié ?",
    de: "Passwort vergessen?",
    it: "Password dimenticata?",
    pt: "Esqueceu a senha?",
    nl: "Wachtwoord vergeten?",
    ar: "هل نسيت كلمة المرور؟",
    el: "Ξεχάσατε τον κωδικό σας;",
    zh: "忘记密码？",
    ja: "パスワードをお忘れですか？",
  },
  "auth.forgotPasswordSubtitle": {
    en: "Enter your email and we'll send you a reset link.",
    es: "Ingresa tu correo y te enviaremos un enlace para restablecerla.",
    fr: "Entrez votre e-mail et nous vous enverrons un lien de réinitialisation.",
    de: "Geben Sie Ihre E-Mail ein und wir senden Ihnen einen Link zum Zurücksetzen.",
    it: "Inserisci la tua email e ti invieremo un link per reimpostarla.",
    pt: "Digite seu e-mail e enviaremos um link para redefinição.",
    nl: "Voer uw e-mail in en wij sturen u een resetlink.",
    ar: "أدخل بريدك الإلكتروني وسنرسل لك رابطًا لإعادة التعيين.",
    el: "Εισαγάγετε το email σας και θα σας στείλουμε σύνδεσμο επαναφοράς.",
    zh: "输入您的电子邮件，我们将向您发送重置链接。",
    ja: "メールアドレスを入力すると、パスワード再設定リンクを送信します。",
  },
  "auth.sendResetLink": {
    en: "Send Reset Link",
    es: "Enviar enlace de restablecimiento",
    fr: "Envoyer le lien de réinitialisation",
    de: "Link zum Zurücksetzen senden",
    it: "Invia link di reset",
    pt: "Enviar link de redefinição",
    nl: "Resetlink verzenden",
    ar: "إرسال رابط إعادة التعيين",
    el: "Αποστολή συνδέσμου επαναφοράς",
    zh: "发送重置链接",
    ja: "リセットリンクを送信",
  },
  "auth.checkEmail": {
    en: "Check your email",
    es: "Revisa tu correo",
    fr: "Vérifiez votre e-mail",
    de: "Prüfen Sie Ihre E-Mails",
    it: "Controlla la tua email",
    pt: "Verifique seu e-mail",
    nl: "Controleer uw e-mail",
    ar: "تحقق من بريدك الإلكتروني",
    el: "Ελέγξτε το email σας",
    zh: "检查您的电子邮件",
    ja: "メールを確認",
  },
  "auth.checkEmailSubtitle": {
    en: "We've sent a password reset link to",
    es: "Hemos enviado un enlace para restablecer la contraseña a",
    fr: "Nous avons envoyé un lien de réinitialisation de mot de passe à",
    de: "Wir haben einen Link zum Zurücksetzen des Passworts gesendet an",
    it: "Abbiamo inviato un link per reimpostare la password a",
    pt: "Enviamos um link de redefinição de senha para",
    nl: "We hebben een wachtwoordresetlink gestuurd naar",
    ar: "لقد أرسلنا رابط إعادة تعيين كلمة المرور إلى",
    el: "Στείλαμε έναν σύνδεσμο επαναφοράς κωδικού πρόσβασης στο",
    zh: "我们已向发送密码重置链接",
    ja: "パスワード再設定リンクを送信しました",
  },
  "auth.sendAgain": {
    en: "Send again",
    es: "Enviar de nuevo",
    fr: "Envoyer à nouveau",
    de: "Erneut senden",
    it: "Invia di nuovo",
    pt: "Enviar novamente",
    nl: "Opnieuw verzenden",
    ar: "إرسال مرة أخرى",
    el: "Στείλτε ξανά",
    zh: "再次发送",
    ja: "もう一度送信",
  },
  "dashboard.title": {
    en: "Dashboard",
    es: "Panel",
    fr: "Tableau de bord",
    de: "Dashboard",
    it: "Dashboard",
    pt: "Painel",
    nl: "Dashboard",
    ar: "لوحة المعلومات",
    el: "Πίνακας Ελέγχου",
    zh: "仪表板",
    ja: "ダッシュボード",
  },
  "dashboard.welcome": {
    en: "Welcome back, Alex. Here's your farm overview.",
    es: "Bienvenido de nuevo, Alex. Aquí tienes tu resumen de la finca.",
    fr: "Bon retour, Alex. Voici votre aperçu de la ferme.",
    de: "Willkommen zurück, Alex. Hier ist Ihr Überblick über die Farm.",
    it: "Bentornato, Alex. Ecco la tua panoramica dell'azienda agricola.",
    pt: "Bem-vindo de volta, Alex. Aqui está a visão geral da sua fazenda.",
    nl: "Welkom terug, Alex. Hier is een overzicht van uw boerderij.",
    ar: "مرحبًا بعودتك يا Alex. إليك نظرة عامة على مزرعتك.",
    el: "Καλωσήρθες ξανά, Alex. Εδώ είναι η επισκόπηση του αγροκτήματός σας.",
    zh: "欢迎回来，Alex。这是您的农场概览。",
    ja: "おかえりなさい、Alex。こちらが農場の概要です。",
  },
  "dashboard.stats.totalFields": {
    en: "Total Fields",
    es: "Campos totales",
    fr: "Total des champs",
    de: "Gesamtfelder",
    it: "Campi totali",
    pt: "Total de talhões",
    nl: "Totaal aantal percelen",
    ar: "إجمالي الحقول",
    el: "Σύνολο Αγροτεμαχίων",
    zh: "总田地数",
    ja: "総圃場数",
  },
  "dashboard.stats.totalArea": {
    en: "Total Area",
    es: "Área total",
    fr: "Surface totale",
    de: "Gesamtfläche",
    it: "Area totale",
    pt: "Área total",
    nl: "Totale oppervlakte",
    ar: "إجمالي المساحة",
    el: "Συνολική έκταση",
    zh: "总面积",
    ja: "総面積",
  },
  "dashboard.stats.farmHealth": {
    en: "Farm Health",
    es: "Salud de la finca",
    fr: "Santé de la ferme",
    de: "Betriebszustand",
    it: "Salute azienda",
    pt: "Saúde da fazenda",
    nl: "Boerderijgezondheid",
    ar: "صحة المزرعة",
    el: "Υγεία Αγροκτήματος",
    zh: "农场健康状况",
    ja: "農場の健康状態",
  },
  "dashboard.stats.estRevenue": {
    en: "Est. Revenue",
    es: "Ing. estimado",
    fr: "Revenu estimé",
    de: "Geschätzter Umsatz",
    it: "Ricavi stimati",
    pt: "Receita est.",
    nl: "Geschatte omzet",
    ar: "الإيرادات المقدرة",
    el: "Εκτιμ. έσοδα",
    zh: "预计收入",
    ja: "推定収益",
  },
  "dashboard.chart.revenue": {
    en: "Revenue vs Expenses",
    es: "Ingresos frente a gastos",
    fr: "Revenus vs dépenses",
    de: "Umsatz vs. Ausgaben",
    it: "Ricavi vs spese",
    pt: "Receita x despesas",
    nl: "Omzet vs. kosten",
    ar: "الإيرادات مقابل المصاريف",
    el: "Έσοδα έναντι εξόδων",
    zh: "收入与支出",
    ja: "収益対費用",
  },
  "dashboard.chart.health": {
    en: "Crop Health Overview",
    es: "Resumen de salud del cultivo",
    fr: "Aperçu de la santé des cultures",
    de: "Übersicht über den Pflanzenzustand",
    it: "Panoramica salute colture",
    pt: "Visão geral da saúde das culturas",
    nl: "Overzicht gewasgezondheid",
    ar: "نظرة عامة على صحة المحاصيل",
    el: "Επισκόπηση υγείας καλλιεργειών",
    zh: "作物健康概览",
    ja: "作物の健康状態の概要",
  },
  "auth.passwordHint": {
    en: "Must be at least 8 characters",
    es: "Debe tener al menos 8 caracteres",
    fr: "Doit contenir au moins 8 caractères",
    de: "Muss mindestens 8 Zeichen haben",
    it: "Deve contenere almeno 8 caratteri",
    pt: "Deve ter pelo menos 8 caracteres",
    nl: "Moet minimaal 8 tekens lang zijn",
    ar: "يجب أن تتكون من 8 أحرف على الأقل",
    el: "Πρέπει να έχει τουλάχιστον 8 χαρακτήρες",
    zh: "至少 8 个字符",
    ja: "8文字以上である必要があります",
  },
  "auth.orContinueWith": {
    en: "Or continue with",
    es: "O continúa con",
    fr: "Ou continuer avec",
    de: "Oder weiter mit",
    it: "Oppure continua con",
    pt: "Ou continue com",
    nl: "Of ga verder met",
    ar: "أو تابع باستخدام",
    el: "Ή συνεχίστε με",
    zh: "或继续使用",
    ja: "または次で続行",
  },
  "auth.google": {
    en: "Google",
    es: "Google",
    fr: "Google",
    de: "Google",
    it: "Google",
    pt: "Google",
    nl: "Google",
    ar: "جوجل",
    el: "Google",
    zh: "Google",
    ja: "Google",
  },
  "auth.github": {
    en: "GitHub",
    es: "GitHub",
    fr: "GitHub",
    de: "GitHub",
    it: "GitHub",
    pt: "GitHub",
    nl: "GitHub",
    ar: "GitHub",
    el: "GitHub",
    zh: "GitHub",
    ja: "GitHub",
  },
  "auth.registerTitle": {
    en: "Start Your Journey",
    es: "Comienza tu viaje",
    fr: "Commencez votre voyage",
    de: "Beginnen Sie Ihre Reise",
    it: "Inizia il tuo viaggio",
    pt: "Comece sua jornada",
    nl: "Begin uw reis",
    ar: "ابدأ رحلتك",
    el: "Ξεκινήστε το ταξίδι σας",
    zh: "开始您的旅程",
    ja: "旅を始めましょう",
  },
  "auth.registerSubtitle": {
    en: "Join thousands of modern farmers using AgroVision to manage their operations more efficiently.",
    es: "Únete a miles de agricultores modernos que usan AgroVision para gestionar sus operaciones de manera más eficiente.",
    fr: "Rejoignez des milliers d'agriculteurs modernes qui utilisent AgroVision pour gérer leurs opérations plus efficacement.",
    de: "Schließen Sie sich tausenden modernen Landwirten an, die AgroVision nutzen, um ihre Abläufe effizienter zu gestalten.",
    it: "Unisciti a migliaia di agricoltori moderni che usano AgroVision per gestire le loro operazioni in modo più efficiente.",
    pt: "Junte-se a milhares de agricultores modernos que usam AgroVision para gerenciar suas operações com mais eficiência.",
    nl: "Sluit je aan bij duizenden moderne boeren die AgroVision gebruiken om hun bedrijfsvoering efficiënter te beheren.",
    ar: "انضم إلى آلاف المزارعين الحديثين الذين يستخدمون AgroVision لإدارة عملياتهم بكفاءة أكبر.",
    el: "Γίνετε μέλος χιλιάδων σύγχρονων αγροτών που χρησιμοποιούν το AgroVision για την πιο αποτελεσματική διαχείριση των εργασιών τους.",
    zh: "加入成千上万使用 AgroVision 的现代农民，共同更高效地管理运营。",
    ja: "AgroVisionを使って業務をより効率的に管理している何千人もの現代の農家に参加しましょう。",
  },
  "auth.resetTitle": {
    en: "No worries",
    es: "No hay problema",
    fr: "Pas de souci",
    de: "Keine Sorge",
    it: "Nessun problema",
    pt: "Sem problemas",
    nl: "Geen zorgen",
    ar: "لا تقلق",
    el: "Δεν υπάρχει πρόβλημα",
    zh: "不用担心",
    ja: "心配ありません",
  },
  "auth.resetSubtitle": {
    en: "We'll help you recover access to your account quickly and securely.",
    es: "Te ayudaremos a recuperar el acceso a tu cuenta de forma rápida y segura.",
    fr: "Nous vous aiderons à récupérer l'accès à votre compte rapidement et en toute sécurité.",
    de: "Wir helfen Ihnen, den Zugriff auf Ihr Konto schnell und sicher wiederherzustellen.",
    it: "Ti aiuteremo a recuperare l'accesso al tuo account in modo rapido e sicuro.",
    pt: "Vamos ajudá-lo a recuperar o acesso à sua conta de forma rápida e segura.",
    nl: "We helpen u snel en veilig weer toegang tot uw account te krijgen.",
    ar: "سنوفر لك المساعدة في استعادة الوصول إلى حسابك بسرعة وأمان.",
    el: "Θα σας βοηθήσουμε να ανακτήσετε την πρόσβαση στο λογαριασμό σας γρήγορα και με ασφάλεια.",
    zh: "我们将帮助您快速安全地恢复账户访问。",
    ja: "迅速かつ安全にアカウントへのアクセスを回復できるようお手伝いします。",
  },
  "landing.heroBadge": {
    en: "The Future of Farm Management",
    es: "El futuro de la gestión agrícola",
    fr: "L'avenir de la gestion agricole",
    de: "Die Zukunft des Farmmanagements",
    it: "Il futuro della gestione agricola",
    pt: "O futuro da gestão agrícola",
    nl: "De toekomst van agrarisch management",
    ar: "مستقبل إدارة المزارع",
    el: "Το μέλλον της διαχείρισης αγροκτημάτων",
    zh: "农场管理的未来",
    ja: "農場管理の未来",
  },
  "landing.heroTitle": {
    en: "The Digital Twin of Your Farm",
    es: "El gemelo digital de tu granja",
    fr: "Le jumeau numérique de votre ferme",
    de: "Der digitale Zwilling Ihrer Farm",
    it: "Il gemello digitale della tua azienda agricola",
    pt: "O gêmeo digital da sua fazenda",
    nl: "De digitale tweeling van uw boerderij",
    ar: "النموذج الرقمي لمزرعتك",
    el: "Το ψηφιακό δίδυμο του αγροκτήματός σας",
    zh: "您农场的数字孪生",
    ja: "あなたの農場のデジタルツイン",
  },
  "landing.heroSubtitle": {
    en: "Manage your fields, animals, machinery, workers, and finances from one intelligent platform powered by AI and real-time data.",
    es: "Gestiona tus campos, animales, maquinaria, trabajadores y finanzas desde una plataforma inteligente impulsada por IA y datos en tiempo real.",
    fr: "Gérez vos champs, animaux, machines, travailleurs et finances depuis une seule plateforme intelligente alimentée par l'IA et les données en temps réel.",
    de: "Verwalten Sie Ihre Felder, Tiere, Maschinen, Mitarbeiter und Finanzen über eine intelligente Plattform, die von KI und Echtzeitdaten angetrieben wird.",
    it: "Gestisci i tuoi campi, animali, macchinari, lavoratori e finanze da una singola piattaforma intelligente alimentata da intelligenza artificiale e dati in tempo reale.",
    pt: "Gerencie seus talhões, animais, máquinas, trabalhadores e finanças em uma única plataforma inteligente impulsionada por IA e dados em tempo real.",
    nl: "Beheer uw percelen, dieren, machines, werknemers en financiën vanuit één intelligente platform, aangedreven door AI en realtime gegevens.",
    ar: "أدر حقولك وحيواناتك وآلاتك وموظفيك وماليك من منصة ذكية واحدة مدعومة بالذكاء الاصطناعي والبيانات في الوقت الفعلي.",
    el: "Διαχειριστείτε τα αγροτεμάχιά σας, τα ζώα, τα μηχανήματα, τους εργαζόμενους και τα οικονομικά σας από μία έξυπνη πλατφόρμα που υποστηρίζεται από AI και δεδομένα σε πραγματικό χρόνο.",
    zh: "通过由 AI 和实时数据驱动的智能平台，统一管理您的田地、动物、机械、员工和财务。",
    ja: "AIとリアルタイムデータに支えられた一つのインテリジェントなプラットフォームから、圃場・動物・機械・作業員・財務を管理します。",
  },
  "landing.heroPrimary": {
    en: "Get Started Free",
    es: "Comenzar gratis",
    fr: "Commencer gratuitement",
    de: "Kostenlos starten",
    it: "Inizia gratis",
    pt: "Comece grátis",
    nl: "Gratis beginnen",
    ar: "ابدأ مجانًا",
    el: "Ξεκινήστε δωρεάν",
    zh: "免费开始",
    ja: "無料で始める",
  },
  "landing.heroSecondary": {
    en: "Watch Demo",
    es: "Ver demo",
    fr: "Voir la démo",
    de: "Demo ansehen",
    it: "Guarda la demo",
    pt: "Ver demonstração",
    nl: "Bekijk demo",
    ar: "شاهد العرض التوضيحي",
    el: "Δείτε την επίδειξη",
    zh: "观看演示",
    ja: "デモを見る",
  },
  "landing.heroNoCard": {
    en: "No credit card required",
    es: "No se requiere tarjeta de crédito",
    fr: "Aucune carte de crédit requise",
    de: "Keine Kreditkarte erforderlich",
    it: "Nessuna carta di credito richiesta",
    pt: "Nenhum cartão de crédito é necessário",
    nl: "Geen creditcard vereist",
    ar: "لا حاجة إلى بطاقة ائتمان",
    el: "Δεν απαιτείται πιστωτική κάρτα",
    zh: "无需信用卡",
    ja: "クレジットカード不要",
  },
  "landing.heroTrial": {
    en: "14-day free trial",
    es: "Prueba gratuita de 14 días",
    fr: "Essai gratuit de 14 jours",
    de: "14 Tage kostenlose Testversion",
    it: "Prova gratuita di 14 giorni",
    pt: "Teste gratuito de 14 dias",
    nl: "14 dagen gratis proef",
    ar: "تجربة مجانية لمدة 14 يومًا",
    el: "Δωρεάν δοκιμή 14 ημερών",
    zh: "14天免费试用",
    ja: "14日間の無料トライアル",
  },
  "landing.heroCancel": {
    en: "Cancel anytime",
    es: "Cancela en cualquier momento",
    fr: "Annulez à tout moment",
    de: "Jederzeit kündbar",
    it: "Annulla in qualsiasi momento",
    pt: "Cancele a qualquer momento",
    nl: "Op elk moment opzeggen",
    ar: "يمكن الإلغاء في أي وقت",
    el: "Ακύρωση ανά πάσα στιγμή",
    zh: "随时取消",
    ja: "いつでもキャンセル可能",
  },
  "landing.featuresBadge": {
    en: "Features",
    es: "Funciones",
    fr: "Fonctionnalités",
    de: "Funktionen",
    it: "Funzionalità",
    pt: "Recursos",
    nl: "Functies",
    ar: "الميزات",
    el: "Χαρακτηριστικά",
    zh: "功能",
    ja: "機能",
  },
  "landing.featuresTitle": {
    en: "Everything you need to manage your farm",
    es: "Todo lo que necesitas para gestionar tu granja",
    fr: "Tout ce dont vous avez besoin pour gérer votre ferme",
    de: "Alles, was Sie für die Verwaltung Ihrer Farm benötigen",
    it: "Tutto ciò di cui hai bisogno per gestire la tua azienda agricola",
    pt: "Tudo o que você precisa para gerenciar sua fazenda",
    nl: "Alles wat je nodig hebt om je boerderij te beheren",
    ar: "كل ما تحتاجه لإدارة مزرعتك",
    el: "Όλα όσα χρειάζεστε για τη διαχείριση του αγροκτήματός σας",
    zh: "管理农场所需的一切",
    ja: "農場を管理するために必要なものすべて",
  },
  "landing.featuresSubtitle": {
    en: "From satellite monitoring to AI-powered recommendations, AgroVision gives you complete control.",
    es: "Desde el monitoreo por satélite hasta recomendaciones impulsadas por IA, AgroVision te da control total.",
    fr: "De la surveillance par satellite aux recommandations alimentées par l'IA, AgroVision vous donne un contrôle total.",
    de: "Von der Satellitenüberwachung bis zu KI-gestützten Empfehlungen gibt AgroVision Ihnen volle Kontrolle.",
    it: "Dal monitoraggio satellitare alle raccomandazioni basate sull'IA, AgroVision ti dà il pieno controllo.",
    pt: "Do monitoramento por satélite às recomendações impulsionadas por IA, o AgroVision oferece controle total.",
    nl: "Van satellietbewaking tot AI-gestuurde aanbevelingen: AgroVision geeft je volledige controle.",
    ar: "من مراقبة الأقمار الصناعية إلى التوصيات المدعومة بالذكاء الاصطناعي، يمنحك AgroVision السيطرة الكاملة.",
    el: "Από την παρακολούθηση μέσω δορυφόρου έως τις συστάσεις που υποστηρίζονται από AI, το AgroVision σας δίνει πλήρη έλεγχο.",
    zh: "从卫星监测到 AI 驱动的建议，AgroVision 为您提供完全控制。",
    ja: "衛星モニタリングからAIによる推奨まで、AgroVisionは完全な制御を提供します。",
  },
  "landing.previewBadge": {
    en: "Dashboard Preview",
    es: "Vista previa del panel",
    fr: "Aperçu du tableau de bord",
    de: "Dashboard-Vorschau",
    it: "Anteprima dashboard",
    pt: "Pré-visualização do painel",
    nl: "Dashboardvoorbeeld",
    ar: "معاينة لوحة المعلومات",
    el: "Προεπισκόπηση πίνακα ελέγχου",
    zh: "仪表板预览",
    ja: "ダッシュボードプレビュー",
  },
  "landing.previewTitle": {
    en: "Beautiful, intuitive, and powerful dashboard",
    es: "Un panel hermoso, intuitivo y potente",
    fr: "Un tableau de bord beau, intuitif et puissant",
    de: "Ein wunderschönes, intuitives und leistungsstarkes Dashboard",
    it: "Una dashboard bella, intuitiva e potente",
    pt: "Um painel bonito, intuitivo e poderoso",
    nl: "Een prachtig, intuïtief en krachtig dashboard",
    ar: "لوحة معلومات جميلة وبديهية وقوية",
    el: "Ένας όμορφος, διαισθητικός και ισχυρός πίνακας ελέγχου",
    zh: "美观、直观且强大的仪表板",
    ja: "美しく、直感的で強力なダッシュボード",
  },
  "landing.navFeatures": {
    en: "Features",
    es: "Funciones",
    fr: "Fonctionnalités",
    de: "Funktionen",
    it: "Funzionalità",
    pt: "Recursos",
    nl: "Functies",
    ar: "الميزات",
    el: "Χαρακτηριστικά",
    zh: "功能",
    ja: "機能",
  },
  "landing.navDashboard": {
    en: "Dashboard",
    es: "Panel",
    fr: "Tableau de bord",
    de: "Dashboard",
    it: "Dashboard",
    pt: "Painel",
    nl: "Dashboard",
    ar: "لوحة المعلومات",
    el: "Πίνακας Ελέγχου",
    zh: "仪表板",
    ja: "ダッシュボード",
  },
  "landing.navPricing": {
    en: "Pricing",
    es: "Precios",
    fr: "Tarifs",
    de: "Preise",
    it: "Prezzi",
    pt: "Preços",
    nl: "Prijzen",
    ar: "الأسعار",
    el: "Τιμολόγηση",
    zh: "价格",
    ja: "料金",
  },
"landing.navFaq": {
    en: "FAQ",
    es: "Preguntas frecuentes",
    fr: "FAQ",
    de: "FAQ",
    it: "FAQ",
    pt: "Perguntas frequentes",
    nl: "Veelgestelde vragen",
    ar: "الأسئلة الشائعة",
    el: "Συχνές Ερωτήσεις",
    zh: "常见问题",
    ja: "FAQ",
  },
  "landing.navAbout": {
    en: "About",
    es: "Acerca de",
    fr: "À propos",
    de: "Über",
    it: "Informazioni",
    pt: "Sobre",
    nl: "Over",
    ar: "حول",
    el: "Σχετικά",
    zh: "关于",
    ja: "会社概要",
  },
  "landing.feature.mapTitle": {
    en: "Interactive Farm Map",
    es: "Mapa interactivo de la granja",
    fr: "Carte interactive de la ferme",
    de: "Interaktive Farmkarte",
    it: "Mappa interattiva dell'azienda",
    pt: "Mapa interativo da fazenda",
    nl: "Interactieve boerderijkaart",
    ar: "خريطة مزرعة تفاعلية",
    el: "Διαδραστικός χάρτης αγροκτήματος",
    zh: "互动农场地图",
    ja: "インタラクティブな農場マップ",
  },
  "landing.feature.mapDescription": {
    en: "Visualize your entire farm with satellite imagery. Draw field boundaries, monitor crop health, and track resources in real time.",
    es: "Visualiza toda tu granja con imágenes satelitales. Dibuja límites de campo, monitorea la salud del cultivo y rastrea recursos en tiempo real.",
    fr: "Visualisez toute votre ferme avec des images satellitaires. Tracez les limites des champs, surveillez la santé des cultures et suivez les ressources en temps réel.",
    de: "Visualisieren Sie Ihre gesamte Farm mit Satellitenbildern. Zeichnen Sie Feldgrenzen, überwachen Sie den Pflanzenzustand und verfolgen Sie Ressourcen in Echtzeit.",
    it: "Visualizza l'intera azienda con immagini satellitari. Disegna i confini dei campi, monitora la salute delle colture e traccia le risorse in tempo reale.",
    pt: "Visualize toda a sua fazenda com imagens de satélite. Desenhe limites de talhão, monitore a saúde das culturas e acompanhe recursos em tempo real.",
    nl: "Visualiseer uw hele boerderij met satellietbeelden. Teken perceelgrenzen, volg gewasgezondheid en houd middelen in realtime bij.",
    ar: "اعرض مزرعتك بالكامل باستخدام صور الأقمار الصناعية. ارسم حدود الحقول وراقب صحة المحاصيل وتتبع الموارد في الوقت الفعلي.",
    el: "Οπτικοποιήστε ολόκληρο το αγρόκτημά σας με δορυφορικές εικόνες. Σχεδιάστε όρια αγροτεμαχίων, παρακολουθήστε την υγεία των καλλιεργειών και εντοπίστε πόρους σε πραγματικό χρόνο.",
    zh: "通过卫星图像可视化整个农场。绘制田块边界、监测作物健康状况并实时跟踪资源。",
    ja: "衛星画像で農場全体を可視化します。圃場境界を描画し、作物の健康状態を監視し、資源をリアルタイムで追跡します。",
  },
  "landing.feature.aiTitle": {
    en: "AI Assistant",
    es: "Asistente de IA",
    fr: "Assistant IA",
    de: "KI-Assistent",
    it: "Assistente AI",
    pt: "Assistente de IA",
    nl: "AI-assistent",
    ar: "مساعد الذكاء الاصطناعي",
    el: "Βοηθός AI",
    zh: "AI 助手",
    ja: "AIアシスタント",
  },
  "landing.feature.aiDescription": {
    en: "Get intelligent recommendations on irrigation, pest control, and yield optimization powered by machine learning.",
    es: "Obtén recomendaciones inteligentes sobre riego, control de plagas y optimización del rendimiento impulsadas por el aprendizaje automático.",
    fr: "Obtenez des recommandations intelligentes sur l'irrigation, la lutte antiparasitaire et l'optimisation du rendement grâce à l'apprentissage automatique.",
    de: "Erhalten Sie intelligente Empfehlungen zu Bewässerung, Schädlingsbekämpfung und Ertragsoptimierung mithilfe von Machine Learning.",
    it: "Ricevi raccomandazioni intelligenti su irrigazione, controllo dei parassiti e ottimizzazione della resa grazie al machine learning.",
    pt: "Receba recomendações inteligentes sobre irrigação, controle de pragas e otimização de rendimento com o apoio de aprendizado de máquina.",
    nl: "Krijg intelligente aanbevelingen voor irrigatie, plaagbestrijding en opbrengstoptimalisatie op basis van machine learning.",
    ar: "احصل على توصيات ذكية بشأن الري ومكافحة الآفات وتحسين الإنتاجية مدعومة بالتعلم الآلي.",
    el: "Λάβετε έξυπνες συστάσεις για άρδευση, αντιμετώπιση παρασίτων και βελτιστοποίηση απόδοσης με υποστήριξη μηχανικής μάθησης.",
    zh: "获得关于灌溉、病虫害控制和产量优化的智能建议，由机器学习驱动。",
    ja: "機械学習に基づく、灌漑・害虫防除・収量最適化に関するインテリジェントな推奨を受け取ります。",
  },
  "landing.feature.analyticsTitle": {
    en: "Advanced Analytics",
    es: "Analítica avanzada",
    fr: "Analytique avancée",
    de: "Erweiterte Analytik",
    it: "Analisi avanzate",
    pt: "Análises avançadas",
    nl: "Geavanceerde analyses",
    ar: "تحليلات متقدمة",
    el: "Προχωρημένη ανάλυση",
    zh: "高级分析",
    ja: "高度な分析",
  },
  "landing.feature.analyticsDescription": {
    en: "Track income, expenses, crop health, and yield predictions with beautiful interactive charts and reports.",
    es: "Haz seguimiento a ingresos, gastos, salud de cultivos y predicciones de rendimiento con hermosos gráficos e informes interactivos.",
    fr: "Suivez les revenus, les dépenses, la santé des cultures et les prévisions de rendement grâce à de beaux graphiques et rapports interactifs.",
    de: "Verfolgen Sie Einnahmen, Ausgaben, Pflanzenzustand und Ertragsprognosen mit schönen interaktiven Diagrammen und Berichten.",
    it: "Traccia entrate, spese, salute delle colture e previsioni di resa con bellissimi grafici e report interattivi.",
    pt: "Acompanhe receitas, despesas, saúde das culturas e previsões de rendimento com gráficos e relatórios interativos e bonitos.",
    nl: "Volg inkomsten, uitgaven, gewasgezondheid en opbrengstprognoses met prachtige interactieve grafieken en rapporten.",
    ar: "تابع الدخل والنفقات وصحة المحاصيل والتنبؤات بالإنتاج مع رسومات وتقارير تفاعلية جميلة.",
    el: "Παρακολουθήστε τα έσοδα, τα έξοδα, την υγεία των καλλιεργειών και τις προβλέψεις απόδοσης με όμορφα διαδραστικά γραφήματα και αναφορές.",
    zh: "通过美观的交互式图表和报告跟踪收入、支出、作物健康状况和产量预测。",
    ja: "美しくインタラクティブなチャートとレポートで、収益、費用、作物の健康状態、収量予測を追跡します。",
  },
  "landing.feature.fleetTitle": {
    en: "Fleet Management",
    es: "Gestión de flotas",
    fr: "Gestion de flotte",
    de: "Flottenmanagement",
    it: "Gestione della flotta",
    pt: "Gerenciamento de frota",
    nl: "Vlootbeheer",
    ar: "إدارة الأسطول",
    el: "Διαχείριση στόλου",
    zh: "车队管理",
    ja: "車両管理",
  },
  "landing.feature.fleetDescription": {
    en: "Monitor all your machinery in one place. Track hours, fuel, maintenance schedules, and worker assignments.",
    es: "Monitorea toda tu maquinaria en un solo lugar. Rastrea horas, combustible, horarios de mantenimiento y asignaciones de trabajadores.",
    fr: "Surveillez toute votre machinerie en un seul endroit. Suivez les heures, le carburant, les calendriers d'entretien et les affectations du personnel.",
    de: "Beobachten Sie alle Ihre Maschinen an einem Ort. Verfolgen Sie Stunden, Kraftstoff, Wartungspläne und Mitarbeiterzuweisungen.",
    it: "Monitora tutte le tue macchine in un unico posto. Traccia ore, carburante, programmi di manutenzione e assegnazioni dei lavoratori.",
    pt: "Monitore toda a sua maquinaria em um só lugar. Acompanhe horas, combustível, cronogramas de manutenção e alocação de trabalhadores.",
    nl: "Volg al uw machines op één plek. Houd uren, brandstof, onderhoudsplannen en werkertoewijzingen bij.",
    ar: "راقب جميع آلاتك في مكان واحد. وتتبع الساعات والوقود وجداول الصيانة وتعيينات العمال.",
    el: "Παρακολουθήστε όλα τα μηχανήματά σας σε ένα μέρος. Παρακολουθήστε ώρες, καύσιμα, προγράμματα συντήρησης και αναθέσεις εργαζομένων.",
    zh: "在一个地方监控所有机械。跟踪工时、燃料、维护计划和工人分配。",
    ja: "すべての機械を一か所で監視します。稼働時間、燃料、メンテナンス予定、作業員の割り当てを追跡します。",
  },
  "landing.feature.weatherTitle": {
    en: "Weather Intelligence",
    es: "Inteligencia del clima",
    fr: "Intelligence météorologique",
    de: "Wetter-Intelligenz",
    it: "Intelligenza meteo",
    pt: "Inteligência do tempo",
    nl: "Weerintelligentie",
    ar: "ذكاء الطقس",
    el: "Έξυπνη πρόγνωση καιρού",
    zh: "天气智能",
    ja: "天気インテリジェンス",
  },
  "landing.feature.weatherDescription": {
    en: "Hyper-local weather forecasts with irrigation and spraying recommendations tailored to your fields.",
    es: "Pronósticos meteorológicos hiperlocales con recomendaciones de riego y aspersión adaptadas a tus campos.",
    fr: "Prévisions météorologiques hyperlocales avec des recommandations d'irrigation et de pulvérisation adaptées à vos champs.",
    de: "Hyperlokale Wettervorhersagen mit auf Ihre Felder zugeschnittenen Empfehlungen zur Bewässerung und zum Sprühen.",
    it: "Previsioni meteo iperlocali con raccomandazioni per irrigazione e spruzzatura adattate ai tuoi campi.",
    pt: "Previsões meteorológicas hiperlocais com recomendações de irrigação e pulverização adaptadas aos seus talhões.",
    nl: "Hyperlokale weersvoorspellingen met irrigatie- en sprayaanbevelingen afgestemd op uw percelen.",
    ar: "توقعات جوية موضعية للغاية مع توصيات للري والرش تتناسب مع حقولك.",
    el: "Υπερτοπικές προγνώσεις καιρού με συστάσεις άρδευσης και ψεκασμού προσαρμοσμένες στα αγροτεμάχιά σας.",
    zh: "针对您田地量身定制的超本地天气预报，以及灌溉和喷洒建议。",
    ja: "圃場に合わせた超ローカルな天気予報と、灌漑・散布の推奨事項。",
  },
  "landing.feature.controlTitle": {
    en: "Complete Control",
    es: "Control total",
    fr: "Contrôle total",
    de: "Volle Kontrolle",
    it: "Controllo completo",
    pt: "Controle completo",
    nl: "Volledige controle",
    ar: "تحكم كامل",
    el: "Πλήρης έλεγχος",
    zh: "全面控制",
    ja: "完全な制御",
  },
  "landing.feature.controlDescription": {
    en: "Manage workers, tasks, animals, inventory, and finances with a comprehensive, all-in-one dashboard.",
    es: "Gestiona trabajadores, tareas, animales, inventario y finanzas con un panel integral y todo en uno.",
    fr: "Gérez les travailleurs, les tâches, les animaux, l'inventaire et les finances grâce à un tableau de bord complet et tout-en-un.",
    de: "Verwalten Sie Mitarbeiter, Aufgaben, Tiere, Inventar und Finanzen mit einem umfassenden All-in-One-Dashboard.",
    it: "Gestisci lavoratori, attività, animali, inventario e finanze con una dashboard completa e tutto in uno.",
    pt: "Gerencie trabalhadores, tarefas, animais, estoque e finanças com um painel completo e tudo em um só lugar.",
    nl: "Beheer medewerkers, taken, dieren, voorraad en financiën met één uitgebreid dashboard.",
    ar: "إدارة العمال والمهام والحيوانات والمخزون والمالية من خلال لوحة معلومات شاملة ومتكاملة.",
    el: "Διαχειριστείτε εργαζομένους, εργασίες, ζώα, αποθέματα και οικονομικά με έναν ολοκληρωμένο πίνακα ελέγχου.",
    zh: "通过一个全面的一体化仪表板管理员工、任务、动物、库存和财务。",
    ja: "従業員、タスク、動物、在庫、財務をまとめて管理できる包括的なオールインワンダッシュボード。",
  },
  "landing.testimonialsBadge": {
    en: "Testimonials",
    es: "Testimonios",
    fr: "Témoignages",
    de: "Testimonials",
    it: "Testimonianze",
    pt: "Depoimentos",
    nl: "Getuigenissen",
    ar: "الشهادات",
    el: "Μαρτυρίες",
    zh: "客户评价",
    ja: "お客様の声",
  },
  "landing.testimonialsTitle": {
    en: "Trusted by farmers worldwide",
    es: "Con la confianza de agricultores de todo el mundo",
    fr: "Fait confiance par des agriculteurs du monde entier",
    de: "Vertrauen von Landwirten weltweit",
    it: "Apprezzato dagli agricoltori di tutto il mondo",
    pt: "Confiado por agricultores de todo o mundo",
    nl: "Vertrouwd door boeren over de hele wereld",
    ar: "موثوق به من قبل المزارعين في جميع أنحاء العالم",
    el: "Αξιόπιστο από αγρότες σε όλο τον κόσμο",
    zh: "受到全球农民信赖",
    ja: "世界中の農家に信頼されています",
  },
  "landing.pricingBadge": {
    en: "Pricing",
    es: "Precios",
    fr: "Tarifs",
    de: "Preise",
    it: "Prezzi",
    pt: "Preços",
    nl: "Prijzen",
    ar: "الأسعار",
    el: "Τιμολόγηση",
    zh: "价格",
    ja: "料金",
  },
  "landing.pricingTitle": {
    en: "Simple, transparent pricing",
    es: "Precios simples y transparentes",
    fr: "Tarification simple et transparente",
    de: "Einfache, transparente Preise",
    it: "Prezzi semplici e trasparenti",
    pt: "Preços simples e transparentes",
    nl: "Eenvoudige, transparante prijzen",
    ar: "أسعار بسيطة وشفافة",
    el: "Απλή και διαφανής τιμολόγηση",
    zh: "简单、透明的价格",
    ja: "シンプルで透明性のある料金",
  },
  "landing.pricingMostPopular": {
    en: "Most Popular",
    es: "Más popular",
    fr: "Le plus populaire",
    de: "Am beliebtesten",
    it: "Più popolare",
    pt: "Mais popular",
    nl: "Meest populair",
    ar: "الأكثر شعبية",
    el: "Πιο δημοφιλές",
    zh: "最受欢迎",
    ja: "最も人気",
  },
  "landing.pricingStartFreeTrial": {
    en: "Start Free Trial",
    es: "Comenzar prueba gratuita",
    fr: "Commencer l'essai gratuit",
    de: "Kostenlose Testversion starten",
    it: "Inizia la prova gratuita",
    pt: "Comece o teste gratuito",
    nl: "Start gratis proefperiode",
    ar: "ابدأ التجربة المجانية",
    el: "Έναρξη δωρεάν δοκιμής",
    zh: "开始免费试用",
    ja: "無料トライアルを開始",
  },
  "landing.pricingGetStarted": {
    en: "Get Started",
    es: "Comenzar",
    fr: "Commencer",
    de: "Loslegen",
    it: "Inizia",
    pt: "Começar",
    nl: "Aan de slag",
    ar: "ابدأ الآن",
    el: "Έναρξη",
    zh: "开始使用",
    ja: "始める",
  },
  "landing.faqBadge": {
    en: "FAQ",
    es: "Preguntas frecuentes",
    fr: "FAQ",
    de: "FAQ",
    it: "FAQ",
    pt: "Perguntas frequentes",
    nl: "Veelgestelde vragen",
    ar: "الأسئلة الشائعة",
    el: "Συχνές Ερωτήσεις",
    zh: "常见问题",
    ja: "FAQ",
  },
  "landing.faqTitle": {
    en: "Frequently asked questions",
    es: "Preguntas frecuentes",
    fr: "Questions fréquentes",
    de: "Häufig gestellte Fragen",
    it: "Domande frequenti",
    pt: "Perguntas frequentes",
    nl: "Veelgestelde vragen",
    ar: "الأسئلة المتكررة",
    el: "Συχνές ερωτήσεις",
    zh: "常见问题",
    ja: "よくある質問",
  },
  "landing.ctaTitle": {
    en: "Ready to transform your farm?",
    es: "¿Listo para transformar tu granja?",
    fr: "Prêt à transformer votre ferme ?",
    de: "Bereit, Ihre Farm zu transformieren?",
    it: "Pronto a trasformare la tua azienda agricola?",
    pt: "Pronto para transformar sua fazenda?",
    nl: "Klaar om uw boerderij te transformeren?",
    ar: "هل أنت مستعد لتحويل مزرعتك؟",
    el: "Έτοιμοι να μεταμορφώσετε το αγρόκτημά σας;",
    zh: "准备好改变您的农场了吗？",
    ja: "あなたの農場を変革する準備ができましたか？",
  },
  "landing.ctaSubtitle": {
    en: "Join thousands of farmers already using AgroVision. Start your free 14-day trial today.",
    es: "Únete a miles de agricultores que ya usan AgroVision. Inicia tu prueba gratuita de 14 días hoy.",
    fr: "Rejoignez des milliers d'agriculteurs qui utilisent déjà AgroVision. Commencez votre essai gratuit de 14 jours dès aujourd'hui.",
    de: "Schließen Sie sich Tausenden von Landwirten an, die AgroVision bereits nutzen. Starten Sie noch heute Ihre kostenlose 14-Tage-Testversion.",
    it: "Unisciti a migliaia di agricoltori che usano già AgroVision. Inizia la tua prova gratuita di 14 giorni oggi stesso.",
    pt: "Junte-se a milhares de agricultores que já usam o AgroVision. Comece seu teste gratuito de 14 dias hoje.",
    nl: "Sluit je aan bij duizenden boeren die AgroVision al gebruiken. Start vandaag je gratis proefperiode van 14 dagen.",
    ar: "انضم إلى آلاف المزارعين الذين يستخدمون AgroVision بالفعل. ابدأ تجربتك المجانية لمدة 14 يومًا اليوم.",
    el: "Γίνετε μέλος χιλιάδων αγροτών που ήδη χρησιμοποιούν το AgroVision. Ξεκινήστε τη δωρεάν δοκιμή 14 ημερών σήμερα.",
    zh: "加入已经在使用 AgroVision 的数千名农民。今天就开始您的 14 天免费试用。",
    ja: "すでにAgroVisionを使っている何千人もの農家に参加しましょう。今日から14日間の無料トライアルを開始してください。",
  },
  "landing.ctaPlaceholder": {
    en: "Enter your email",
    es: "Ingresa tu correo electrónico",
    fr: "Entrez votre e-mail",
    de: "Geben Sie Ihre E-Mail ein",
    it: "Inserisci la tua email",
    pt: "Digite seu e-mail",
    nl: "Voer uw e-mailadres in",
    ar: "أدخل بريدك الإلكتروني",
    el: "Εισαγάγετε το email σας",
    zh: "输入您的电子邮件",
    ja: "メールアドレスを入力",
  },
  "landing.ctaButton": {
    en: "Get Started",
    es: "Comenzar",
    fr: "Commencer",
    de: "Loslegen",
    it: "Inizia",
    pt: "Começar",
    nl: "Aan de slag",
    ar: "ابدأ الآن",
    el: "Έναρξη",
    zh: "开始使用",
    ja: "始める",
  },
  "landing.footerProduct": {
    en: "Product",
    es: "Producto",
    fr: "Produit",
    de: "Produkt",
    it: "Prodotto",
    pt: "Produto",
    nl: "Product",
    ar: "المنتج",
    el: "Προϊόν",
    zh: "产品",
    ja: "製品",
  },
  "landing.footerCompany": {
    en: "Company",
    es: "Empresa",
    fr: "Entreprise",
    de: "Unternehmen",
    it: "Azienda",
    pt: "Empresa",
    nl: "Bedrijf",
    ar: "الشركة",
    el: "Εταιρεία",
    zh: "公司",
    ja: "会社",
  },
  "landing.footerLegal": {
    en: "Legal",
    es: "Legal",
    fr: "Légal",
    de: "Rechtliches",
    it: "Legale",
    pt: "Jurídico",
    nl: "Juridisch",
    ar: "قانوني",
    el: "Νομικό",
    zh: "法律",
    ja: "法務",
  },
  "landing.footerFeatures": {
    en: "Features",
    es: "Funciones",
    fr: "Fonctionnalités",
    de: "Funktionen",
    it: "Funzionalità",
    pt: "Recursos",
    nl: "Functies",
    ar: "الميزات",
    el: "Χαρακτηριστικά",
    zh: "功能",
    ja: "機能",
  },
  "landing.footerPricing": {
    en: "Pricing",
    es: "Precios",
    fr: "Tarifs",
    de: "Preise",
    it: "Prezzi",
    pt: "Preços",
    nl: "Prijzen",
    ar: "الأسعار",
    el: "Τιμολόγηση",
    zh: "价格",
    ja: "料金",
  },
  "landing.footerDashboard": {
    en: "Dashboard",
    es: "Panel",
    fr: "Tableau de bord",
    de: "Dashboard",
    it: "Dashboard",
    pt: "Painel",
    nl: "Dashboard",
    ar: "لوحة المعلومات",
    el: "Πίνακας Ελέγχου",
    zh: "仪表板",
    ja: "ダッシュボード",
  },
  "landing.footerIntegrations": {
    en: "Integrations",
    es: "Integraciones",
    fr: "Intégrations",
    de: "Integrationen",
    it: "Integrazioni",
    pt: "Integrações",
    nl: "Integraties",
    ar: "التكاملات",
    el: "Ενσωματώσεις",
    zh: "集成",
    ja: "統合",
  },
  "landing.footerAbout": {
    en: "About",
    es: "Acerca de",
    fr: "À propos",
    de: "Über",
    it: "Informazioni",
    pt: "Sobre",
    nl: "Over",
    ar: "حول",
    el: "Σχετικά",
    zh: "关于",
    ja: "会社概要",
  },
  "landing.footerBlog": {
    en: "Blog",
    es: "Blog",
    fr: "Blog",
    de: "Blog",
    it: "Blog",
    pt: "Blog",
    nl: "Blog",
    ar: "المدونة",
    el: "Ιστολόγιο",
    zh: "博客",
    ja: "ブログ",
  },
  "landing.footerCareers": {
    en: "Careers",
    es: "Empleo",
    fr: "Carrières",
    de: "Karriere",
    it: "Carriere",
    pt: "Carreiras",
    nl: "Vacatures",
    ar: "الوظائف",
    el: "Θέσεις εργασίας",
    zh: "职业",
    ja: "採用情報",
  },
  "landing.footerContact": {
    en: "Contact",
    es: "Contacto",
    fr: "Contact",
    de: "Kontakt",
    it: "Contatti",
    pt: "Contato",
    nl: "Contact",
    ar: "اتصل",
    el: "Επικοινωνία",
    zh: "联系",
    ja: "お問い合わせ",
  },
  "landing.footerPrivacy": {
    en: "Privacy",
    es: "Privacidad",
    fr: "Confidentialité",
    de: "Datenschutz",
    it: "Privacy",
    pt: "Privacidade",
    nl: "Privacy",
    ar: "الخصوصية",
    el: "Απόρρητο",
    zh: "隐私",
    ja: "プライバシー",
  },
  "landing.footerTerms": {
    en: "Terms",
    es: "Términos",
    fr: "Conditions",
    de: "Nutzungsbedingungen",
    it: "Termini",
    pt: "Termos",
    nl: "Voorwaarden",
    ar: "الشروط",
    el: "Όροι",
    zh: "条款",
    ja: "利用規約",
  },
  "landing.footerSecurity": {
    en: "Security",
    es: "Seguridad",
    fr: "Sécurité",
    de: "Sicherheit",
    it: "Sicurezza",
    pt: "Segurança",
    nl: "Beveiliging",
    ar: "الأمان",
    el: "Ασφάλεια",
    zh: "安全",
    ja: "セキュリティ",
  },
  "landing.footerCookies": {
    en: "Cookies",
    es: "Cookies",
    fr: "Cookies",
    de: "Cookies",
    it: "Cookie",
    pt: "Cookies",
    nl: "Cookies",
    ar: "ملفات تعريف الارتباط",
    el: "Cookies",
    zh: "Cookies",
    ja: "クッキー",
  },
  "landing.footerDescription": {
    en: "The intelligent platform for modern farm management.",
    es: "La plataforma inteligente para la gestión agrícola moderna.",
    fr: "La plateforme intelligente pour la gestion moderne des fermes.",
    de: "Die intelligente Plattform für modernes Farmmanagement.",
    it: "La piattaforma intelligente per la gestione moderna delle aziende agricole.",
    pt: "A plataforma inteligente para o gerenciamento moderno de fazendas.",
    nl: "Het intelligente platform voor modern boerderijmanagement.",
    ar: "المنصة الذكية لإدارة المزارع الحديثة.",
    el: "Η έξυπνη πλατφόρμα για τη σύγχρονη διαχείριση αγροκτημάτων.",
    zh: "现代农场管理的智能平台。",
    ja: "現代の農場管理のためのインテリジェントなプラットフォーム。",
  },
  "landing.footerRights": {
    en: "© 2024 AgroVision. All rights reserved.",
    es: "© 2024 AgroVision. Todos los derechos reservados.",
    fr: "© 2024 AgroVision. Tous droits réservés.",
    de: "© 2024 AgroVision. Alle Rechte vorbehalten.",
    it: "© 2024 AgroVision. Tutti i diritti riservati.",
    pt: "© 2024 AgroVision. Todos os direitos reservados.",
    nl: "© 2024 AgroVision. Alle rechten voorbehouden.",
    ar: "© 2024 AgroVision. جميع الحقوق محفوظة.",
    el: "© 2024 AgroVision. Με επιφύλαξη παντός δικαιώματος.",
    zh: "© 2024 AgroVision。保留所有权利。",
    ja: "© 2024 AgroVision. All rights reserved.",
  },
  "landing.previewStatFields": {
    en: "Total Fields",
    es: "Total de campos",
    fr: "Total des champs",
    de: "Felder gesamt",
    it: "Campi totali",
    pt: "Total de talhões",
    nl: "Totaal percelen",
    ar: "إجمالي الحقول",
    el: "Σύνολο αγροτεμαχίων",
    zh: "田地总数",
    ja: "圃場数",
  },
  "landing.previewStatArea": {
    en: "Total Area",
    es: "Área total",
    fr: "Superficie totale",
    de: "Gesamtfläche",
    it: "Superficie totale",
    pt: "Área total",
    nl: "Totale oppervlakte",
    ar: "إجمالي المساحة",
    el: "Συνολική έκταση",
    zh: "总面积",
    ja: "総面積",
  },
  "landing.previewStatHealth": {
    en: "Farm Health",
    es: "Salud de la granja",
    fr: "Santé de la ferme",
    de: "Farmgesundheit",
    it: "Salute dell'azienda",
    pt: "Saúde da fazenda",
    nl: "Boerderijgezondheid",
    ar: "صحة المزرعة",
    el: "Υγεία αγροκτήματος",
    zh: "农场健康",
    ja: "農場の健康状態",
  },
  "landing.previewStatRevenue": {
    en: "Est. Revenue",
    es: "Ingresos est.",
    fr: "Revenu estimé",
    de: "Geschätzter Umsatz",
    it: "Ricavi stim.",
    pt: "Receita est.",
    nl: "Geschatte omzet",
    ar: "الإيرادات المقدرة",
    el: "Εκτιμώμενα έσοδα",
    zh: "预计收入",
    ja: "推定収益",
  },
  "landing.previewCropHealth": {
    en: "Crop Health Overview",
    es: "Resumen de salud de los cultivos",
    fr: "Aperçu de la santé des cultures",
    de: "Übersicht über den Pflanzenzustand",
    it: "Panoramica della salute delle colture",
    pt: "Visão geral da saúde das culturas",
    nl: "Overzicht gewasgezondheid",
    ar: "نظرة عامة على صحة المحاصيل",
    el: "Επισκόπηση υγείας καλλιεργειών",
    zh: "作物健康概览",
    ja: "作物の健康状態の概要",
  },
  "landing.previewWeather": {
    en: "Weather",
    es: "Clima",
    fr: "Météo",
    de: "Wetter",
    it: "Meteo",
    pt: "Tempo",
    nl: "Weer",
    ar: "الطقس",
    el: "Καιρός",
    zh: "天气",
    ja: "天気",
  },
  "landing.previewWeatherCloudy": {
    en: "Partly Cloudy",
    es: "Parcialmente nublado",
    fr: "Partiellement nuageux",
    de: "Teilweise bewölkt",
    it: "Parzialmente nuvoloso",
    pt: "Parcialmente nublado",
    nl: "Gedeeltelijk bewolkt",
    ar: "غائم جزئيًا",
    el: "Μερικώς συννεφιασμένος",
    zh: "局部多云",
    ja: "所により曇り",
  },
  "landing.pricingStarterName": {
    en: "Starter",
    es: "Inicial",
    fr: "Débutant",
    de: "Starter",
    it: "Starter",
    pt: "Iniciante",
    nl: "Starter",
    ar: "البدء",
    el: "Αρχικό",
    zh: "入门版",
    ja: "スターター",
  },
  "landing.pricingStarterDescription": {
    en: "Perfect for small family farms",
    es: "Perfecto para pequeñas granjas familiares",
    fr: "Parfait pour les petites fermes familiales",
    de: "Perfekt für kleine Familienbetriebe",
    it: "Perfetto per piccole aziende agricole familiari",
    pt: "Perfeito para pequenas fazendas familiares",
    nl: "Perfect voor kleine familieboerderijen",
    ar: "مثالي للمزارع العائلية الصغيرة",
    el: "Ιδανικό για μικρές οικογενειακές φάρμες",
    zh: "非常适合小型家庭农场",
    ja: "小規模な家族農場に最適",
  },
  "landing.pricingProfessionalName": {
    en: "Professional",
    es: "Profesional",
    fr: "Professionnel",
    de: "Professionell",
    it: "Professionale",
    pt: "Profissional",
    nl: "Professioneel",
    ar: "احترافي",
    el: "Επαγγελματικό",
    zh: "专业版",
    ja: "プロフェッショナル",
  },
  "landing.pricingProfessionalDescription": {
    en: "Ideal for growing operations",
    es: "Ideal para operaciones en crecimiento",
    fr: "Idéal pour les opérations en croissance",
    de: "Ideal für wachsende Betriebe",
    it: "Ideale per operazioni in crescita",
    pt: "Ideal para operações em crescimento",
    nl: "Ideaal voor groeiende bedrijfsactiviteiten",
    ar: "مثالي للعمليات المتنامية",
    el: "Ιδανικό για αναπτυσσόμενες δραστηριότητες",
    zh: "非常适合成长中的业务",
    ja: "成長する事業に最適",
  },
  "landing.pricingEnterpriseName": {
    en: "Enterprise",
    es: "Empresa",
    fr: "Entreprise",
    de: "Unternehmen",
    it: "Enterprise",
    pt: "Empresa",
    nl: "Enterprise",
    ar: "مؤسسة",
    el: "Εταιρικό",
    zh: "企业版",
    ja: "エンタープライズ",
  },
  "landing.pricingEnterpriseDescription": {
    en: "For large-scale farming operations",
    es: "Para operaciones agrícolas a gran escala",
    fr: "Pour les opérations agricoles à grande échelle",
    de: "Für großflächige Landwirtschaftsbetriebe",
    it: "Per operazioni agricole su larga scala",
    pt: "Para operações agrícolas em grande escala",
    nl: "Voor grootschalige landbouwoperaties",
    ar: "لعمليات الزراعة واسعة النطاق",
    el: "Για μεγάλες αγροτικές επιχειρήσεις",
    zh: "适用于大规模农业运营",
    ja: "大規模な農業運営向け",
  },
  "landing.faqMapQuestion": {
    en: "How does the interactive farm map work?",
    es: "¿Cómo funciona el mapa interactivo de la granja?",
    fr: "Comment fonctionne la carte interactive de la ferme ?",
    de: "Wie funktioniert die interaktive Farmkarte?",
    it: "Come funziona la mappa interattiva dell'azienda?",
    pt: "Como funciona o mapa interativo da fazenda?",
    nl: "Hoe werkt de interactieve boerderijkaart?",
    ar: "كيف تعمل خريطة المزرعة التفاعلية؟",
    el: "Πώς λειτουργεί ο διαδραστικός χάρτης του αγροκτήματος;",
    zh: "互动农场地图是如何工作的？",
    ja: "インタラクティブな農場マップはどのように動作しますか？",
  },
  "landing.faqMapAnswer": {
    en: "AgroVision uses satellite imagery to create a digital twin of your farm. You can draw field boundaries, monitor crop health through NDVI analysis, and track field activities in real time.",
    es: "AgroVision usa imágenes satelitales para crear un gemelo digital de tu granja. Puedes dibujar límites de campo, monitorear la salud del cultivo a través del análisis NDVI y rastrear actividades de campo en tiempo real.",
    fr: "AgroVision utilise des images satellitaires pour créer un jumeau numérique de votre ferme. Vous pouvez dessiner les limites des champs, surveiller la santé des cultures grâce à l'analyse NDVI et suivre les activités des champs en temps réel.",
    de: "AgroVision nutzt Satellitenbilder, um einen digitalen Zwilling Ihrer Farm zu erstellen. Sie können Feldgrenzen zeichnen, den Pflanzenzustand über NDVI-Analysen überwachen und Feldaktivitäten in Echtzeit verfolgen.",
    it: "AgroVision utilizza immagini satellitari per creare un gemello digitale della tua azienda agricola. Puoi disegnare i confini dei campi, monitorare la salute delle colture tramite analisi NDVI e tracciare le attività di campo in tempo reale.",
    pt: "O AgroVision usa imagens de satélite para criar um gêmeo digital da sua fazenda. Você pode desenhar limites de talhões, monitorar a saúde das culturas por meio de análise NDVI e acompanhar atividades de campo em tempo real.",
    nl: "AgroVision gebruikt satellietbeelden om een digitale tweeling van uw boerderij te creëren. U kunt perceelgrenzen tekenen, gewasgezondheid volgen via NDVI-analyse en veldactiviteiten in realtime volgen.",
    ar: "يستخدم AgroVision صور الأقمار الصناعية لإنشاء نموذج رقمي لمزرعتك. يمكنك رسم حدود الحقول ومراقبة صحة المحاصيل من خلال تحليل NDVI وتتبع أنشطة الحقول في الوقت الفعلي.",
    el: "Το AgroVision χρησιμοποιεί δορυφορικές εικόνες για να δημιουργήσει ένα ψηφιακό δίδυμο του αγροκτήματός σας. Μπορείτε να σχεδιάσετε όρια αγροτεμαχίων, να παρακολουθήσετε την υγεία των καλλιεργειών μέσω ανάλυσης NDVI και να παρακολουθήσετε δραστηριότητες αγρού σε πραγματικό χρόνο.",
    zh: "AgroVision 使用卫星影像创建您农场的数字孪生。您可以绘制田块边界、通过 NDVI 分析监控作物健康，并实时跟踪田间活动。",
    ja: "AgroVisionは衛星画像を使用して農場のデジタルツインを作成します。圃場境界を描画し、NDVI分析で作物の健康状態を監視し、圃場活動をリアルタイムで追跡できます。",
  },
  "landing.faqEquipmentQuestion": {
    en: "Can I integrate with my existing equipment?",
    es: "¿Puedo integrarme con mi equipo existente?",
    fr: "Puis-je m'intégrer à mon équipement existant ?",
    de: "Kann ich meine bestehende Ausrüstung integrieren?",
    it: "Posso integrarmi con le attrezzature esistenti?",
    pt: "Posso integrar com meu equipamento existente?",
    nl: "Kan ik integreren met mijn bestaande apparatuur?",
    ar: "هل يمكنني التكامل مع المعدات الحالية؟",
    el: "Μπορώ να ενσωματωθώ με τον υπάρχοντα εξοπλισμό μου;",
    zh: "我可以与现有设备集成吗？",
    ja: "既存の機器と統合できますか？",
  },
  "landing.faqEquipmentAnswer": {
    en: "Yes! AgroVision supports integration with most modern farm equipment through API connections and IoT sensors. We support John Deere, Case IH, and many more.",
    es: "¡Sí! AgroVision admite integración con la mayoría del equipo agrícola moderno mediante conexiones API y sensores IoT. Soportamos John Deere, Case IH y muchos más.",
    fr: "Oui ! AgroVision prend en charge l'intégration avec la plupart des équipements agricoles modernes via des connexions API et des capteurs IoT. Nous prenons en charge John Deere, Case IH et bien d'autres.",
    de: "Ja! AgroVision unterstützt die Integration der meisten modernen Landmaschinen über API-Verbindungen und IoT-Sensoren. Wir unterstützen John Deere, Case IH und viele weitere.",
    it: "Sì! AgroVision supporta l'integrazione con la maggior parte delle attrezzature agricole moderne tramite connessioni API e sensori IoT. Supportiamo John Deere, Case IH e molti altri.",
    pt: "Sim! O AgroVision suporta integração com a maioria dos equipamentos agrícolas modernos por meio de conexões de API e sensores IoT. Apoiamo John Deere, Case IH e muitos outros.",
    nl: "Ja! AgroVision ondersteunt integratie met de meeste moderne landbouwapparatuur via API-verbindingen en IoT-sensoren. We ondersteunen John Deere, Case IH en vele anderen.",
    ar: "نعم! يدعم AgroVision التكامل مع معظم معدات الزراعة الحديثة من خلال اتصالات API وأجهزة استشعار إنترنت الأشياء. ونحن ندعم John Deere و Case IH والكثير غيرها.",
    el: "Ναι! Το AgroVision υποστηρίζει ενσωμάτωση με τα περισσότερα σύγχρονα αγροτικά μηχανήματα μέσω συνδέσεων API και αισθητήρων IoT. Υποστηρίζουμε John Deere, Case IH και πολλά άλλα.",
    zh: "可以！AgroVision 支持通过 API 连接和物联网传感器与大多数现代农机设备集成。我们支持约翰迪尔、Case IH 等众多品牌。",
    ja: "はい！AgroVisionは、API接続とIoTセンサーを通じて、ほとんどの最新の農業機器との統合をサポートしています。John Deere、Case IHなど多くの機器をサポートしています。",
  },
  "landing.faqAccuracyQuestion": {
    en: "How accurate is the AI assistant?",
    es: "¿Qué tan precisa es la asistente de IA?",
    fr: "À quel point l'assistant IA est-il précis ?",
    de: "Wie genau ist der KI-Assistent?",
    it: "Quanto è accurato l'assistente AI?",
    pt: "Quão precisa é a assistente de IA?",
    nl: "Hoe accuraat is de AI-assistent?",
    ar: "ما مدى دقة مساعد الذكاء الاصطناعي؟",
    el: "Πόσο ακριβής είναι ο βοηθός AI;",
    zh: "AI 助手有多准确？",
    ja: "AIアシスタントの精度はどのくらいですか？",
  },
  "landing.faqAccuracyAnswer": {
    en: "Our AI models are trained on millions of agricultural data points and achieve over 90% accuracy in recommendations. We continuously update models based on the latest research.",
    es: "Nuestros modelos de IA se entrenan con millones de puntos de datos agrícolas y logran una precisión superior al 90% en las recomendaciones. Actualizamos continuamente los modelos según la investigación más reciente.",
    fr: "Nos modèles d'IA sont entraînés sur des millions de données agricoles et atteignent plus de 90 % de précision dans les recommandations. Nous mettons continuellement à jour les modèles en fonction des dernières recherches.",
    de: "Unsere KI-Modelle werden mit Millionen landwirtschaftlicher Datenpunkte trainiert und erreichen in Empfehlungen eine Genauigkeit von über 90 %. Wir aktualisieren die Modelle kontinuierlich auf Basis der neuesten Forschung.",
    it: "I nostri modelli AI vengono addestrati su milioni di punti dati agricoli e raggiungono oltre il 90% di accuratezza nelle raccomandazioni. Aggiorniamo continuamente i modelli in base alle ultime ricerche.",
    pt: "Nossos modelos de IA são treinados com milhões de pontos de dados agrícolas e alcançam mais de 90% de precisão nas recomendações. Atualizamos continuamente os modelos com base nas pesquisas mais recentes.",
    nl: "Onze AI-modellen zijn getraind op miljoenen landbouwgegevens en bereiken een nauwkeurigheid van meer dan 90% in aanbevelingen. We werken de modellen voortdurend bij op basis van het nieuwste onderzoek.",
    ar: "تم تدريب نماذج الذكاء الاصطناعي لدينا على ملايين نقاط البيانات الزراعية وتحقق دقة تزيد عن 90% في التوصيات. نقوم بتحديث النماذج باستمرار بناءً على أحدث الأبحاث.",
    el: "Τα μοντέλα AI μας εκπαιδεύονται σε εκατομμύρια αγροτικά δεδομένα και επιτυγχάνουν πάνω από 90% ακρίβεια στις συστάσεις. Ενημερώνουμε συνεχώς τα μοντέλα με βάση την πιο πρόσφατη έρευνα.",
    zh: "我们的 AI 模型基于数百万农业数据点训练，推荐准确率超过 90%。我们根据最新研究持续更新模型。",
    ja: "当社のAIモデルは数百万件の農業データで学習され、推奨の精度は90％以上です。最新の研究に基づいてモデルを継続的に更新しています。",
  },
  "landing.faqSecurityQuestion": {
    en: "Is my farm data secure?",
    es: "¿Es segura la información de mi granja?",
    fr: "Mes données de ferme sont-elles sécurisées ?",
    de: "Sind meine Farmdaten sicher?",
    it: "I dati della mia azienda sono sicuri?",
    pt: "Os dados da minha fazenda são seguros?",
    nl: "Zijn mijn boerderijgegevens veilig?",
    ar: "هل بيانات مزرعتي آمنة؟",
    el: "Είναι ασφαλή τα δεδομένα του αγροκτήματός μου;",
    zh: "我的农场数据安全吗？",
    ja: "農場データは安全ですか？",
  },
  "landing.faqSecurityAnswer": {
    en: "Absolutely. We use enterprise-grade encryption for all data. Your farm data is encrypted at rest and in transit. We never share your data with third parties.",
    es: "Absolutamente. Usamos cifrado de nivel empresarial para todos los datos. Los datos de tu granja están cifrados tanto en reposo como en tránsito. Nunca compartimos tus datos con terceros.",
    fr: "Absolument. Nous utilisons un chiffrement de niveau entreprise pour toutes les données. Les données de votre ferme sont chiffrées au repos et en transit. Nous ne partageons jamais vos données avec des tiers.",
    de: "Absolut. Wir verwenden Verschlüsselung auf Unternehmensniveau für alle Daten. Ihre Farmdaten sind sowohl im Ruhezustand als auch im Transit verschlüsselt. Wir geben Ihre Daten niemals an Dritte weiter.",
    it: "Assolutamente. Utilizziamo crittografia di livello enterprise per tutti i dati. I dati della tua azienda sono crittografati a riposo e in transito. Non condividiamo mai i tuoi dati con terzi.",
    pt: "Absolutamente. Usamos criptografia de nível empresarial para todos os dados. Os dados da sua fazenda são criptografados em repouso e em trânsito. Nunca compartilhamos seus dados com terceiros.",
    nl: "Absoluut. We gebruiken encryptie op ondernemingsniveau voor alle gegevens. Uw boerderijgegevens zijn zowel in rust als in transit versleuteld. We delen uw gegevens nooit met derden.",
    ar: "بالتأكيد. نحن نستخدم تشفيرًا على مستوى المؤسسات لجميع البيانات. بيانات مزرعتك مشفرة أثناء الراحة وأثناء النقل. لا نشارك بياناتك مع أطراف ثالثة أبدًا.",
    el: "Απολύτως. Χρησιμοποιούμε κρυπτογράφηση εταιρικού επιπέδου για όλα τα δεδομένα. Τα δεδομένα του αγροκτήματός σας είναι κρυπτογραφημένα τόσο στην ηρεμία όσο και κατά τη μετάδοση. Δεν μοιραζόμαστε ποτέ τα δεδομένα σας με τρίτους.",
    zh: "当然。我们对所有数据使用企业级加密。您的农场数据在静态和传输过程中都经过加密。我们绝不会与第三方共享您的数据。",
    ja: "もちろんです。すべてのデータに企業グレードの暗号化を使用しています。農場データは保存時も送信時も暗号化されています。第三者とデータを共有することはありません。",
  },
  "landing.faqSupportQuestion": {
    en: "What if I need help getting started?",
    es: "¿Qué pasa si necesito ayuda para comenzar?",
    fr: "Et si j'ai besoin d'aide pour commencer ?",
    de: "Was ist, wenn ich Hilfe beim Einstieg brauche?",
    it: "E se ho bisogno di aiuto per iniziare?",
    pt: "E se eu precisar de ajuda para começar?",
    nl: "Wat als ik hulp nodig heb bij het starten?",
    ar: "ماذا لو احتجت إلى مساعدة للبدء؟",
    el: "Τι γίνεται αν χρειάζομαι βοήθεια για να ξεκινήσω;",
    zh: "如果我在开始时需要帮助怎么办？",
    ja: "始めるにあたって助けが必要な場合はどうすればよいですか？",
  },
  "landing.faqSupportAnswer": {
    en: "Every plan includes onboarding support. Our team of agricultural technology experts will help you set up your digital farm and train your team.",
    es: "Cada plan incluye soporte de incorporación. Nuestro equipo de expertos en tecnología agrícola le ayudará a configurar su granja digital y capacitar a su equipo.",
    fr: "Chaque forfait comprend un accompagnement à l'onboarding. Notre équipe d'experts en technologie agricole vous aidera à mettre en place votre ferme numérique et à former votre équipe.",
    de: "Jeder Plan umfasst Onboarding-Support. Unser Team aus Agrartechnologie-Experten hilft Ihnen bei der Einrichtung Ihrer digitalen Farm und der Schulung Ihres Teams.",
    it: "Ogni piano include supporto per l'onboarding. Il nostro team di esperti di tecnologia agricola ti aiuterà a impostare la tua fattoria digitale e a formare il tuo team.",
    pt: "Todos os planos incluem suporte de onboarding. Nossa equipe de especialistas em tecnologia agrícola ajudará você a configurar sua fazenda digital e treinar sua equipe.",
    nl: "Elk plan omvat onboarding-ondersteuning. Ons team van experts op het gebied van agrotechnologie helpt u bij het opzetten van uw digitale boerderij en het trainen van uw team.",
    ar: "يتضمن كل خطة دعمًا للتأسيس. سيساعدك فريق خبراء التكنولوجيا الزراعية على إعداد مزرعتك الرقمية وتدريب فريقك.",
    el: "Κάθε πακέτο περιλαμβάνει υποστήριξη onboarding. Η ομάδα μας ειδικών στην αγροτική τεχνολογία θα σας βοηθήσει να δημιουργήσετε το ψηφιακό σας αγρόκτημα και να εκπαιδεύσετε την ομάδα σας.",
    zh: "每个方案都包括入门支持。我们的农业技术专家团队将帮助您搭建数字化农场并培训您的团队。",
    ja: "すべてのプランにはオンボーディングサポートが含まれます。農業技術の専門家チームが、デジタル農場のセットアップとチームのトレーニングを支援します。",
  },
  "landing.faqTrialQuestion": {
    en: "Can I try before buying?",
    es: "¿Puedo probar antes de comprar?",
    fr: "Puis-je essayer avant d'acheter ?",
    de: "Kann ich vorher testen?",
    it: "Posso provare prima di acquistare?",
    pt: "Posso experimentar antes de comprar?",
    nl: "Kan ik eerst proberen voordat ik koop?",
    ar: "هل يمكنني التجربة قبل الشراء؟",
    el: "Μπορώ να δοκιμάσω πριν αγοράσω;",
    zh: "我可以先试用再购买吗？",
    ja: "購入前に試用できますか？",
  },
  "landing.faqTrialAnswer": {
    en: "Yes! We offer a 14-day free trial with full access to all features. No credit card required.",
    es: "¡Sí! Ofrecemos una prueba gratuita de 14 días con acceso completo a todas las funciones. No se requiere tarjeta de crédito.",
    fr: "Oui ! Nous proposons un essai gratuit de 14 jours avec un accès complet à toutes les fonctionnalités. Aucune carte de crédit n'est requise.",
    de: "Ja! Wir bieten eine kostenlose 14-Tage-Testversion mit vollem Zugriff auf alle Funktionen an. Keine Kreditkarte erforderlich.",
    it: "Sì! Offriamo una prova gratuita di 14 giorni con accesso completo a tutte le funzioni. Nessuna carta di credito richiesta.",
    pt: "Sim! Oferecemos um teste gratuito de 14 dias com acesso total a todos os recursos. Nenhum cartão de crédito é necessário.",
    nl: "Ja! We bieden een gratis proefperiode van 14 dagen met volledige toegang tot alle functies. Geen creditcard nodig.",
    ar: "نعم! نقدم تجربة مجانية لمدة 14 يومًا مع وصول كامل إلى جميع الميزات. لا حاجة إلى بطاقة ائتمان.",
    el: "Ναι! Προσφέρουμε δωρεάν δοκιμή 14 ημερών με πλήρη πρόσβαση σε όλες τις λειτουργίες. Δεν απαιτείται πιστωτική κάρτα.",
    zh: "可以！我们提供为期 14 天的免费试用，完整访问所有功能。无需信用卡。",
    ja: "はい！14日間の無料トライアルを提供しており、すべての機能にフルアクセスできます。クレジットカードは不要です。",
  },
  "landing.testimonialSarahName": {
    en: "Sarah Mitchell",
    es: "Sarah Mitchell",
    fr: "Sarah Mitchell",
    de: "Sarah Mitchell",
    it: "Sarah Mitchell",
    pt: "Sarah Mitchell",
    nl: "Sarah Mitchell",
    ar: "سارة ميتشل",
    el: "Sarah Mitchell",
    zh: "Sarah Mitchell",
    ja: "Sarah Mitchell",
  },
  "landing.testimonialSarahRole": {
    en: "Third-Generation Farmer",
    es: "Agricultora de tercera generación",
    fr: "Agricultrice de troisième génération",
    de: "Landwirtin der dritten Generation",
    it: "Agricoltrice di terza generazione",
    pt: "Agricultora de terceira geração",
    nl: "Boerin uit de derde generatie",
    ar: "مزارعة من الجيل الثالث",
    el: "Αγρότισσα τρίτης γενιάς",
    zh: "第三代农民",
    ja: "3世代目の農家",
  },
  "landing.testimonialSarahContent": {
    en: "AgroVision transformed how we manage our 500-acre farm. The AI recommendations alone saved us 30% on water costs.",
    es: "AgroVision transformó la forma en que gestionamos nuestra granja de 500 acres. Las recomendaciones de IA por sí solas nos ahorraron un 30% en costos de agua.",
    fr: "AgroVision a transformé notre façon de gérer notre ferme de 500 acres. Les recommandations IA nous ont permis d'économiser 30 % sur les coûts d'eau.",
    de: "AgroVision hat verändert, wie wir unsere 500 Hektar große Farm verwalten. Die KI-Empfehlungen allein haben uns 30 % der Wasserkosten gespart.",
    it: "AgroVision ha trasformato il modo in cui gestiamo la nostra azienda agricola di 500 acri. Le sole raccomandazioni AI ci hanno fatto risparmiare il 30% sui costi dell'acqua.",
    pt: "O AgroVision transformou a forma como gerenciamos nossa fazenda de 500 acres. As recomendações de IA sozinhas economizaram 30% nos custos de água.",
    nl: "AgroVision heeft veranderd hoe we onze boerderij van 500 acre beheren. De AI-aanbevelingen alleen al bespaarden ons 30% op waterkosten.",
    ar: "غيّر AgroVision طريقة إدارة مزرعتنا التي تبلغ مساحتها 500 فدان. وفرت توصيات الذكاء الاصطناعي وحدها 30% من تكاليف المياه.",
    el: "Το AgroVision άλλαξε τον τρόπο διαχείρισης του 500-acre αγροκτήματός μας. Οι συστάσεις AI μόνες τους μας έσωσαν 30% στα έξοδα νερού.",
    zh: "AgroVision 改变了我们管理 500 英亩农场的方式。仅 AI 建议就为我们节省了 30% 的水费。",
    ja: "AgroVisionは、500エーカーの農場を管理する方法を変えました。AIの推奨だけで、水道代を30%節約できました。",
  },
  "landing.testimonialSarahLocation": {
    en: "Iowa",
    es: "Iowa",
    fr: "Iowa",
    de: "Iowa",
    it: "Iowa",
    pt: "Iowa",
    nl: "Iowa",
    ar: "آيوا",
    el: "Αϊόβα",
    zh: "爱荷华州",
    ja: "アイオワ州",
  },
  "landing.testimonialJamesName": {
    en: "James Anderson",
    es: "James Anderson",
    fr: "James Anderson",
    de: "James Anderson",
    it: "James Anderson",
    pt: "James Anderson",
    nl: "James Anderson",
    ar: "جيمس أندرسون",
    el: "James Anderson",
    zh: "James Anderson",
    ja: "James Anderson",
  },
  "landing.testimonialJamesRole": {
    en: "AgriTech Consultant",
    es: "Consultor de AgriTech",
    fr: "Consultant AgriTech",
    de: "AgriTech-Berater",
    it: "Consulente AgriTech",
    pt: "Consultor de AgriTech",
    nl: "AgriTech-consultant",
    ar: "مستشار تكنولوجيا الزراعة",
    el: "Σύμβουλος AgriTech",
    zh: "农业科技顾问",
    ja: "アグリテックコンサルタント",
  },
  "landing.testimonialJamesContent": {
    en: "The most intuitive farm management platform I've ever used. The interactive map feature is a game-changer.",
    es: "La plataforma de gestión agrícola más intuitiva que he usado. La función de mapa interactivo es un cambio de juego.",
    fr: "La plateforme de gestion agricole la plus intuitive que j'aie jamais utilisée. La fonction de carte interactive est un véritable atout.",
    de: "Die intuitivste Farmmanagement-Plattform, die ich je benutzt habe. Die Funktion für interaktive Karten ist ein Game-Changer.",
    it: "La piattaforma di gestione agricola più intuitiva che io abbia mai usato. La funzione della mappa interattiva è rivoluzionaria.",
    pt: "A plataforma de gestão agrícola mais intuitiva que já usei. O recurso de mapa interativo é um divisor de águas.",
    nl: "Het meest intuïtieve farmmanagementplatform dat ik ooit heb gebruikt. De interactieve kaartfunctie is een gamechanger.",
    ar: "أكثر منصة إدارة للمزارع بديهية استخدمتها على الإطلاق. ميزة الخريطة التفاعلية هي تغيير جذري.",
    el: "Η πιο διαισθητική πλατφόρμα διαχείρισης αγροκτήματος που έχω χρησιμοποιήσει ποτέ. Το χαρακτηριστικό του διαδραστικού χάρτη είναι πραγματικά καινοτόμο.",
    zh: "这是我用过最直观的农场管理平台。互动地图功能是一个改变游戏规则的功能。",
    ja: "これまで使った中で最も直感的な農場管理プラットフォームです。インタラクティブマップ機能は画期的です。",
  },
  "landing.testimonialJamesLocation": {
    en: "California",
    es: "California",
    fr: "Californie",
    de: "Kalifornien",
    it: "California",
    pt: "Califórnia",
    nl: "Californië",
    ar: "كاليفورنيا",
    el: "Καλιφόρνια",
    zh: "加利福尼亚州",
    ja: "カリフォルニア州",
  },
  "landing.testimonialMariaName": {
    en: "Maria Rodriguez",
    es: "María Rodríguez",
    fr: "Maria Rodriguez",
    de: "Maria Rodriguez",
    it: "Maria Rodriguez",
    pt: "Maria Rodriguez",
    nl: "Maria Rodriguez",
    ar: "ماريا رودريغيز",
    el: "Μαρία Ροντρίγκεζ",
    zh: "Maria Rodriguez",
    ja: "Maria Rodriguez",
  },
  "landing.testimonialMariaRole": {
    en: "Organic Farm Owner",
    es: "Dueña de granja orgánica",
    fr: "Propriétaire de ferme biologique",
    de: "Besitzerin einer Biofarm",
    it: "Proprietaria di un'azienda agricola biologica",
    pt: "Proprietária de fazenda orgânica",
    nl: "Eigenaar van een biologische boerderij",
    ar: "صاحبة مزرعة عضوية",
    el: "Ιδιοκτήτρια βιολογικού αγροκτήματος",
    zh: "有机农场主",
    ja: "有機農場のオーナー",
  },
  "landing.testimonialMariaContent": {
    en: "From crop health monitoring to worker management, AgroVision does it all. It's like having a digital farm manager.",
    es: "Desde el monitoreo de la salud del cultivo hasta la gestión de trabajadores, AgroVision lo hace todo. Es como tener un gerente digital de la granja.",
    fr: "De la surveillance de la santé des cultures à la gestion des travailleurs, AgroVision fait tout. C'est comme avoir un gestionnaire de ferme numérique.",
    de: "Von der Überwachung des Pflanzenzustands bis zur Mitarbeiterführung: AgroVision macht alles. Es ist wie ein digitaler Farmmanager.",
    it: "Dal monitoraggio della salute delle colture alla gestione dei lavoratori, AgroVision fa tutto. È come avere un manager digitale dell'azienda agricola.",
    pt: "Do monitoramento da saúde das culturas ao gerenciamento de trabalhadores, o AgroVision faz tudo. É como ter um gerente digital da fazenda.",
    nl: "Van gewasgezondheidsmonitoring tot personeelsmanagement: AgroVision doet het allemaal. Het is alsof je een digitale boerderijmanager hebt.",
    ar: "من مراقبة صحة المحاصيل إلى إدارة العمال، يقوم AgroVision بكل شيء. إنه مثل وجود مدير رقمي للمزرعة.",
    el: "Από την παρακολούθηση της υγείας των καλλιεργειών έως τη διαχείριση εργαζομένων, το AgroVision κάνει τα πάντα. Είναι σαν να έχεις έναν ψηφιακό διαχειριστή αγροκτήματος.",
    zh: "从作物健康监测到员工管理，AgroVision 一应俱全。它就像拥有一位数字化农场经理。",
    ja: "作物の健康状態の監視から従業員管理まで、AgroVisionはすべて対応します。まるでデジタルなファームマネージャーがいるようです。",
  },
  "landing.testimonialMariaLocation": {
    en: "Texas",
    es: "Texas",
    fr: "Texas",
    de: "Texas",
    it: "Texas",
    pt: "Texas",
    nl: "Texas",
    ar: "تكساس",
    el: "Τέξας",
    zh: "得克萨斯州",
    ja: "テキサス州",
  },
};

interface LanguageContextValue {
  language: AppLanguage;
  setLanguage: (language: AppLanguage) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextValue>({
  language: "en",
  setLanguage: () => {},
  t: (key: string) => key,
});

const i18nInstance = i18next.createInstance();
const translationCacheKey = "agrovizion-translations";

function buildResourcesForLanguage(language: AppLanguage) {
  return Object.entries(translations).reduce<Record<string, string>>((acc, [key, values]) => {
    const translatedValue = values[language];
    if (translatedValue) {
      acc[key] = translatedValue;
    }
    return acc;
  }, {});
}

function buildAllResources() {
  return languageOptions.reduce<Record<string, { translation: Record<string, string> }>>((acc, option) => {
    acc[option.value] = { translation: buildResourcesForLanguage(option.value) };
    return acc;
  }, {});
}

async function initializeI18n() {
  if (i18nInstance.isInitialized) {
    return i18nInstance;
  }

  await i18nInstance.init({
    resources: buildAllResources(),
    lng: "en",
    fallbackLng: "en",
    supportedLngs: languageOptions.map((option) => option.value),
    interpolation: {
      escapeValue: false,
    },
    ns: ["translation"],
    defaultNS: "translation",
  });

  return i18nInstance;
}

function readCachedTranslations(language: AppLanguage) {
  if (typeof window === "undefined") {
    return {} as Record<string, string>;
  }

  try {
    const rawValue = window.localStorage.getItem(`${translationCacheKey}:${language}`);
    return rawValue ? (JSON.parse(rawValue) as Record<string, string>) : {};
  } catch {
    return {} as Record<string, string>;
  }
}

function writeCachedTranslations(language: AppLanguage, resources: Record<string, string>) {
  if (typeof window === "undefined") {
    return;
  }

  try {
    window.localStorage.setItem(`${translationCacheKey}:${language}`, JSON.stringify(resources));
  } catch {
    // Ignore storage failures and continue with runtime fallback.
  }
}

async function loadLibreTranslations(language: AppLanguage) {
  if (language === "en") {
    return;
  }

  const bundledResources = buildResourcesForLanguage(language);
  if (Object.keys(bundledResources).length > 0) {
    i18nInstance.addResourceBundle(language, "translation", bundledResources, true, true);
    return;
  }

  const cachedResources = readCachedTranslations(language);
  if (Object.keys(cachedResources).length > 0) {
    i18nInstance.addResourceBundle(language, "translation", cachedResources, true, true);
    return;
  }

  const englishResources = buildResourcesForLanguage("en");
  const translatedEntries = await Promise.all(
    Object.entries(englishResources).map(async ([key, value]) => {
      try {
        const response = await fetch("https://libretranslate.de/translate", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            q: value,
            source: "en",
            target: language,
            format: "text",
          }),
        });

        if (!response.ok) {
          throw new Error("Translation request failed");
        }

        const data = (await response.json()) as { translatedText?: string };
        return [key, data.translatedText || value] as const;
      } catch {
        return [key, value] as const;
      }
    }),
  );

  const translatedResources = Object.fromEntries(translatedEntries);
  writeCachedTranslations(language, translatedResources);
  i18nInstance.addResourceBundle(language, "translation", translatedResources, true, true);
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<AppLanguage>("en");

  useEffect(() => {
    const applyInitialLanguage = async () => {
      const instance = await initializeI18n();
      const storedLanguage = window.localStorage.getItem("agrovizion-language") as AppLanguage | null;
      const initialLanguage = storedLanguage && languageOptions.some((option) => option.value === storedLanguage)
        ? storedLanguage
        : "en";

      setLanguageState(initialLanguage);
      await instance.changeLanguage(initialLanguage);
      await loadLibreTranslations(initialLanguage);
    };

    void applyInitialLanguage();
  }, []);

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
  }, [language]);

  const setLanguage = async (nextLanguage: AppLanguage) => {
    const resources = buildResourcesForLanguage(nextLanguage);
    i18nInstance.addResourceBundle(nextLanguage, "translation", resources, true, true);

    setLanguageState(nextLanguage);
    window.localStorage.setItem("agrovizion-language", nextLanguage);
    await i18nInstance.changeLanguage(nextLanguage);
    await loadLibreTranslations(nextLanguage);
    document.documentElement.lang = nextLanguage;
    document.documentElement.dir = nextLanguage === "ar" ? "rtl" : "ltr";
  };

  const t = (key: string) => {
    const directTranslation = translations[key]?.[language] ?? translations[key]?.en ?? key;
    if (directTranslation !== key) {
      return directTranslation;
    }

    return i18nInstance.t(key, { lng: language }) || key;
  };

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}
